import { NextResponse } from 'next/server';
import { finalizeSchema } from '@/lib/assignments/submission-domain';
import { createSubmissionObjectStore } from '@/lib/assignments/submission-object-store';
import { finalizeQuestionAsset, getQuestionUploadStatus } from '@/lib/assignments/submission-service';
import { guardSubmissionMutation, readBoundedSubmissionJson, requireStudentActor, submissionErrorResponse } from '@/lib/assignments/submission-route-guards';
import { rethrowIfNextDynamicError } from '@/lib/nextjs-dynamic-error';
import { prisma } from '@/lib/prisma';

export const dynamic = 'force-dynamic';

export async function POST(request: Request, { params }: { params: Promise<{ assignmentId: string; questionId: string }> }) { const auth = await requireStudentActor(); if ('response' in auth) return auth.response; const blocked = await guardSubmissionMutation(request, auth.actor.id, 'upload'); if (blocked) return blocked; try { const ids = await params; const body = finalizeSchema.parse(await readBoundedSubmissionJson(request)); const result = await finalizeQuestionAsset(prisma, createSubmissionObjectStore(), { studentId: auth.actor.id, ...ids, ...body }); if (result.status !== 'READY') return NextResponse.json({ status: result.status, intentId: result.intentId }, { status: result.status === 'SCANNING' ? 202 : result.status === 'EXPIRED' ? 410 : 422 }); const asset = result.asset; return NextResponse.json({ status: 'READY', intentId: asset.id, answerVersion: result.answerVersion, asset: { id: asset.id, displayName: asset.originalName, mimeType: asset.mimeType, sizeBytes: asset.sizeBytes, state: asset.state, finalizedAt: asset.finalizedAt, role: asset.assetRole, orderIndex: asset.orderIndex, embeddedPosition: asset.embeddedPosition } }); } catch (error) { rethrowIfNextDynamicError(error); return submissionErrorResponse(error); } }

export async function GET(request: Request, { params }: { params: Promise<{ assignmentId: string; questionId: string }> }) { const auth = await requireStudentActor(); if ('response' in auth) return auth.response; try { const ids = await params; const intentId = new URL(request.url).searchParams.get('intentId') ?? ''; const result = await getQuestionUploadStatus(prisma, { studentId: auth.actor.id, ...ids, intentId }); if (result.status !== 'READY') return NextResponse.json({ status: result.status, intentId: result.intentId }); const asset = result.asset; return NextResponse.json({ status: 'READY', intentId: asset.id, answerVersion: result.answerVersion, asset: { id: asset.id, displayName: asset.originalName, mimeType: asset.mimeType, sizeBytes: asset.sizeBytes, state: asset.state, finalizedAt: asset.finalizedAt, role: asset.assetRole, orderIndex: asset.orderIndex, embeddedPosition: asset.embeddedPosition } }); } catch (error) { rethrowIfNextDynamicError(error); return submissionErrorResponse(error); } }
