import type { PersonalizationPluginPathPlanningPolicy } from '../types';

export const CONTROL_CORRECTION_PATH_PLANNING_POLICY: PersonalizationPluginPathPlanningPolicy = {
  displayName: '控制系统校正设计',
  checkpointPolicy: {
    minCheckpoints: 1,
    checkpointResourceTypes: ['checkpoint', 'simulation', 'arena_task'],
    requiresTerminalValidation: true,
  },
  allowedResourceMix: [
    'lesson_step',
    'knowledge_card',
    'textbook_section',
    'quiz',
    'adaptive_quiz',
    'control_workbench',
    'simulation',
    'arena_task',
    'external_resource',
    'reflection',
    'checkpoint',
    'ai_intervention',
    'konling',
  ],
  knowledgeTargetAliases: {
    'control-correction:time-domain-targets': [
      '性能指标_1_1',
      '动态性能指标_3_a10733c1',
      '时域指标到目标极点区域_3_36001',
      '稳态误差双路径判断_3_37002',
      '给定-扰动双通道误差分析_3_37001',
    ],
    'control-correction:root-locus-design': [
      '根轨迹_1_1',
      '根轨迹_4_c19f8854',
      '根轨迹完整法则_3_0f2e7b11',
      '根轨迹绘制规则_3_2f9e8cb3',
      '根轨迹增益换算_3_4b1d9e6c',
      '零点引入与根轨迹重排_3_35001',
      '串联校正_6_fede5751',
      '频域PD与超前整定_4_42011',
      '频域PI与滞后整定_4_42010',
      '控制器频域特性矩阵_4_42008',
    ],
    'control-correction:simulation-validation': [
      '对象化三域验证_3_56cb3a4e',
      '传统设计四联图校正_4_47004',
      '跨模型验证比较_4_47006',
      '工程指标代价函数翻译_4_47003',
      '剩余风险说明_4_45006',
    ],
    'control-correction:arena-transfer': [
      '跨模型验证比较_4_47006',
      '传统设计四联图校正_4_47004',
    ],
  },
  starterPathPolicy: {
    policyFamilies: ['foundation-remediation', 'simulation-driven', 'preference-matched'],
    targetOptionCount: 3,
    difficultyRhythm: 'steady',
    allowExternalResources: false,
    preferredResourceTypes: [
      'knowledge_card',
      'textbook_section',
      'lesson_step',
      'quiz',
      'adaptive_quiz',
      'control_workbench',
      'simulation',
      'arena_task',
    ],
  },
  explanationTemplates: {
    ready: '已根据当前证据生成校正设计学习路径。',
    coldStart: '证据还少，先从入门路径开始，系统会随学习过程调整。',
    lowConfidence: '当前证据不足，先沿可执行路径学习，后续会根据新证据调整。',
    fallback: '当前只能给出保守路径建议，请先完成可用资源并补充学习证据。',
  },
  evidenceRequirements: [
    'question',
    'path-execution',
    'simulation-run',
    'arena-official-evaluation',
    'reflection',
  ],
};
