/**
 * 预置教案统一出口
 */

import { LESSON_02_LEGACY_MODELING_PRESET } from './lesson-02-legacy-modeling';
import { LESSON_02_LAPLACE_PRESET } from './lesson-02-laplace';
import { LESSON_01_FEEDBACK_PRESET } from './lesson-01-feedback';
import { LESSON_03_DIFFERENTIAL_MODELING_PRESET } from './lesson-03-differential-modeling';
import { LESSON_04_TRANSFER_FUNCTION_PRESET } from './lesson-04-transfer-function';
import { LESSON_05_STRUCTURE_TOPOLOGY_PRESET } from './lesson-05-structure-topology';
import { LESSON_06_JUDGE_BENCH_PRESET } from './lesson-06-judge-bench';
import { LESSON_07_UNDERDAMPED_PRESET } from './lesson-07-underdamped';
import { LESSON_08_STABILITY_ACCURACY_PRESET } from './lesson-08-stability-accuracy';
import { LESSON_09_CORRECTION_TIME_DOMAIN_PRESET } from './lesson-09-correction-time-domain';
import { LESSON_10_ROOT_LOCUS_PRESET } from './lesson-10-root-locus';
import { LESSON_11_PARAMETER_ROOT_LOCUS_PRESET } from './lesson-11-parameter-root-locus';
import { LESSON_12_FREQUENCY_BODE_PRESET } from './lesson-12-frequency-bode';
import { LESSON_13_PHASE_STABILITY_PRESET } from './lesson-13-phase-stability';
import { LESSON_14_STABILITY_MARGIN_PRESET } from './lesson-14-stability-margin';
import { LESSON_15_SERIES_COMPENSATION_PRESET } from './lesson-15-series-compensation';
import { LESSON_16_NONLINEAR_BASICS_PRESET } from './lesson-16-nonlinear-basics';
import { LESSON_17_DESCRIBING_FUNCTION_PRESET } from './lesson-17-describing-function';

export {
  LESSON_01_FEEDBACK_PRESET,
  LESSON_02_LEGACY_MODELING_PRESET,
  LESSON_02_LAPLACE_PRESET,
  LESSON_03_DIFFERENTIAL_MODELING_PRESET,
  LESSON_04_TRANSFER_FUNCTION_PRESET,
  LESSON_05_STRUCTURE_TOPOLOGY_PRESET,
  LESSON_06_JUDGE_BENCH_PRESET,
  LESSON_07_UNDERDAMPED_PRESET,
  LESSON_08_STABILITY_ACCURACY_PRESET,
  LESSON_09_CORRECTION_TIME_DOMAIN_PRESET,
  LESSON_10_ROOT_LOCUS_PRESET,
  LESSON_11_PARAMETER_ROOT_LOCUS_PRESET,
  LESSON_12_FREQUENCY_BODE_PRESET,
  LESSON_13_PHASE_STABILITY_PRESET,
  LESSON_14_STABILITY_MARGIN_PRESET,
  LESSON_15_SERIES_COMPENSATION_PRESET,
  LESSON_16_NONLINEAR_BASICS_PRESET,
  LESSON_17_DESCRIBING_FUNCTION_PRESET,
};

export const ALL_PRESETS = [
  LESSON_01_FEEDBACK_PRESET,
  LESSON_02_LEGACY_MODELING_PRESET,
  LESSON_02_LAPLACE_PRESET,
  LESSON_03_DIFFERENTIAL_MODELING_PRESET,
  LESSON_04_TRANSFER_FUNCTION_PRESET,
  LESSON_05_STRUCTURE_TOPOLOGY_PRESET,
  LESSON_06_JUDGE_BENCH_PRESET,
  LESSON_07_UNDERDAMPED_PRESET,
  LESSON_08_STABILITY_ACCURACY_PRESET,
  LESSON_09_CORRECTION_TIME_DOMAIN_PRESET,
  LESSON_10_ROOT_LOCUS_PRESET,
  LESSON_11_PARAMETER_ROOT_LOCUS_PRESET,
  LESSON_12_FREQUENCY_BODE_PRESET,
  LESSON_13_PHASE_STABILITY_PRESET,
  LESSON_14_STABILITY_MARGIN_PRESET,
  LESSON_15_SERIES_COMPENSATION_PRESET,
  LESSON_16_NONLINEAR_BASICS_PRESET,
  LESSON_17_DESCRIBING_FUNCTION_PRESET,
];
