/**
 * 预置教案统一出口
 */

import { LESSON_02_LEGACY_MODELING_PRESET } from './lesson-02-legacy-modeling';
import { LESSON_02_LAPLACE_PRESET } from './lesson-02-laplace';
import { LESSON_01_FEEDBACK_PRESET } from './lesson-01-feedback';
import { LESSON_03_DIFFERENTIAL_MODELING_PRESET } from './lesson-03-differential-modeling';
import { LESSON_04_TRANSFER_FUNCTION_PRESET } from './lesson-04-transfer-function';
import { LESSON_05_STRUCTURE_TOPOLOGY_PRESET } from './lesson-05-structure-topology';
import { LESSON_06_JUDGE_BENCH_PRESET } from './lesson-06-judge-bench';
import { LESSON_07_UNDERDAMPED_PRESET } from './lesson-07-underdamped';
import { LESSON_08_STABILITY_ACCURACY_PRESET } from './lesson-08-stability-accuracy';
import { LESSON_09_CORRECTION_TIME_DOMAIN_PRESET } from './lesson-09-correction-time-domain';
import { LESSON_10_ROOT_LOCUS_PRESET } from './lesson-10-root-locus';
import { LESSON_11_PARAMETER_ROOT_LOCUS_PRESET } from './lesson-11-parameter-root-locus';
import { LESSON_12_FREQUENCY_BODE_PRESET } from './lesson-12-frequency-bode';
import { LESSON_13_PHASE_STABILITY_PRESET } from './lesson-13-phase-stability';
import { LESSON_14_STABILITY_MARGIN_PRESET } from './lesson-14-stability-margin';
import { LESSON_15_SERIES_COMPENSATION_PRESET } from './lesson-15-series-compensation';
import { LESSON_16_NONLINEAR_BASICS_PRESET } from './lesson-16-nonlinear-basics';
import { LESSON_17_DESCRIBING_FUNCTION_PRESET } from './lesson-17-describing-function';
import { CRUISE_COMFORT_PRESET } from './cruise-comfort';
import { LSUM_DESIGN_FEASIBLE_DOMAIN_PRESET } from './lsum-design-feasible-domain';
import { UNIT_2_1_MODELING_LANGUAGE_PRESET } from './unit-2-1-modeling-language';
import { UNIT_2_2_TIME_DOMAIN_RESPONSE_PRESET } from './unit-2-2-time-domain-response';
import { UNIT_2_3_FREQUENCY_RESPONSE_BODE_INTRO_PRESET } from './unit-2-3-frequency-response-bode-intro';
import { UNIT_2_4_NYQUIST_MARGIN_ENTRY_PRESET } from './unit-2-4-nyquist-margin-entry';
import { UNIT_3_1_PURE_POLE_STABILITY_AND_DYNAMICS_PRESET } from './unit-3-1-pure-pole-stability-and-dynamics';
import { UNIT_3_2_ROUTH_STABILITY_BOUNDARY_PRESET } from './unit-3-2-routh-stability-boundary';
import { UNIT_3_3_ROOT_LOCUS_RULES_PRESET } from './unit-3-3-root-locus-rules';
import { UNIT_3_4_ROOT_LOCUS_READING_VALIDATION_PRESET } from './unit-3-4-root-locus-reading-validation';
import { UNIT_3_5_ZERO_DYNAMIC_IMPROVEMENT_PRESET } from './unit-3-5-zero-dynamic-improvement';
import { UNIT_3_6_ZERO_DESIGN_WORKSHOP_PRESET } from './unit-3-6-zero-design-workshop';
import { UNIT_3_7_STEADY_ERROR_LOW_FREQUENCY_COMPENSATION_PRESET } from './unit-3-7-steady-error-low-frequency-compensation';
import { UNIT_3_8_FREQUENCY_DOMAIN_TRANSLATION_JUDGMENT_PRESET } from './unit-3-8-frequency-domain-translation-judgment';
import { UNIT_3_9_CROSS_DOMAIN_MAPPING_LAB_PRESET } from './unit-3-9-cross-domain-mapping-lab';
import { UNIT_4_1_DESIGN_TASK_EXPRESSION_PRESET } from './unit-4-1-design-task-expression';
import { UNIT_4_2_CONTROLLER_SELECTION_FIRST_START_PRESET } from './unit-4-2-controller-selection-first-start';
import { UNIT_4_3_INITIAL_SCHEME_PRACTICE_FIRST_VALIDATION_PRESET } from './unit-4-3-initial-scheme-practice-first-validation';
import { UNIT_4_4_FIXED_STRUCTURE_OPTIMIZATION_MODELING_PRESET } from './unit-4-4-fixed-structure-optimization-modeling';
import { UNIT_4_5_CONSTRAINT_AWARE_PARAMETER_OPTIMIZATION_PRESET } from './unit-4-5-constraint-aware-parameter-optimization';
import { UNIT_4_6_FIXED_STRUCTURE_BOUNDARY_STRUCTURAL_ENCODING_PRESET } from './unit-4-6-fixed-structure-boundary-structural-encoding';
import { UNIT_4_7_DESTROYER_HIFI_DESIGN_CLOSURE_PRESET } from './unit-4-7-destroyer-hifi-design-closure';
import { UNIT_5_1_LINEAR_BACKBONE_BOUNDARIES_PRESET } from './unit-5-1-linear-backbone-boundaries';

export {
  LESSON_01_FEEDBACK_PRESET,
  LESSON_02_LEGACY_MODELING_PRESET,
  LESSON_02_LAPLACE_PRESET,
  LESSON_03_DIFFERENTIAL_MODELING_PRESET,
  LESSON_04_TRANSFER_FUNCTION_PRESET,
  LESSON_05_STRUCTURE_TOPOLOGY_PRESET,
  LESSON_06_JUDGE_BENCH_PRESET,
  LESSON_07_UNDERDAMPED_PRESET,
  LESSON_08_STABILITY_ACCURACY_PRESET,
  LESSON_09_CORRECTION_TIME_DOMAIN_PRESET,
  LESSON_10_ROOT_LOCUS_PRESET,
  LESSON_11_PARAMETER_ROOT_LOCUS_PRESET,
  LESSON_12_FREQUENCY_BODE_PRESET,
  LESSON_13_PHASE_STABILITY_PRESET,
  LESSON_14_STABILITY_MARGIN_PRESET,
  LESSON_15_SERIES_COMPENSATION_PRESET,
  LESSON_16_NONLINEAR_BASICS_PRESET,
  LESSON_17_DESCRIBING_FUNCTION_PRESET,
  CRUISE_COMFORT_PRESET,
  LSUM_DESIGN_FEASIBLE_DOMAIN_PRESET,
  UNIT_2_1_MODELING_LANGUAGE_PRESET,
  UNIT_2_2_TIME_DOMAIN_RESPONSE_PRESET,
  UNIT_2_3_FREQUENCY_RESPONSE_BODE_INTRO_PRESET,
  UNIT_2_4_NYQUIST_MARGIN_ENTRY_PRESET,
  UNIT_3_1_PURE_POLE_STABILITY_AND_DYNAMICS_PRESET,
  UNIT_3_2_ROUTH_STABILITY_BOUNDARY_PRESET,
  UNIT_3_3_ROOT_LOCUS_RULES_PRESET,
  UNIT_3_4_ROOT_LOCUS_READING_VALIDATION_PRESET,
  UNIT_3_5_ZERO_DYNAMIC_IMPROVEMENT_PRESET,
  UNIT_3_6_ZERO_DESIGN_WORKSHOP_PRESET,
  UNIT_3_7_STEADY_ERROR_LOW_FREQUENCY_COMPENSATION_PRESET,
  UNIT_3_8_FREQUENCY_DOMAIN_TRANSLATION_JUDGMENT_PRESET,
  UNIT_3_9_CROSS_DOMAIN_MAPPING_LAB_PRESET,
  UNIT_4_1_DESIGN_TASK_EXPRESSION_PRESET,
  UNIT_4_2_CONTROLLER_SELECTION_FIRST_START_PRESET,
  UNIT_4_3_INITIAL_SCHEME_PRACTICE_FIRST_VALIDATION_PRESET,
  UNIT_4_4_FIXED_STRUCTURE_OPTIMIZATION_MODELING_PRESET,
  UNIT_4_5_CONSTRAINT_AWARE_PARAMETER_OPTIMIZATION_PRESET,
  UNIT_4_6_FIXED_STRUCTURE_BOUNDARY_STRUCTURAL_ENCODING_PRESET,
  UNIT_4_7_DESTROYER_HIFI_DESIGN_CLOSURE_PRESET,
  UNIT_5_1_LINEAR_BACKBONE_BOUNDARIES_PRESET,
};

export const ALL_PRESETS = [
  LESSON_01_FEEDBACK_PRESET,
  LESSON_02_LEGACY_MODELING_PRESET,
  LESSON_02_LAPLACE_PRESET,
  LESSON_03_DIFFERENTIAL_MODELING_PRESET,
  LESSON_04_TRANSFER_FUNCTION_PRESET,
  LESSON_05_STRUCTURE_TOPOLOGY_PRESET,
  LESSON_06_JUDGE_BENCH_PRESET,
  LESSON_07_UNDERDAMPED_PRESET,
  LESSON_08_STABILITY_ACCURACY_PRESET,
  LESSON_09_CORRECTION_TIME_DOMAIN_PRESET,
  LESSON_10_ROOT_LOCUS_PRESET,
  LESSON_11_PARAMETER_ROOT_LOCUS_PRESET,
  LESSON_12_FREQUENCY_BODE_PRESET,
  LESSON_13_PHASE_STABILITY_PRESET,
  LESSON_14_STABILITY_MARGIN_PRESET,
  LESSON_15_SERIES_COMPENSATION_PRESET,
  LESSON_16_NONLINEAR_BASICS_PRESET,
  LESSON_17_DESCRIBING_FUNCTION_PRESET,
  CRUISE_COMFORT_PRESET,
  LSUM_DESIGN_FEASIBLE_DOMAIN_PRESET,
  UNIT_2_1_MODELING_LANGUAGE_PRESET,
  UNIT_2_2_TIME_DOMAIN_RESPONSE_PRESET,
  UNIT_2_3_FREQUENCY_RESPONSE_BODE_INTRO_PRESET,
  UNIT_2_4_NYQUIST_MARGIN_ENTRY_PRESET,
  UNIT_3_1_PURE_POLE_STABILITY_AND_DYNAMICS_PRESET,
  UNIT_3_2_ROUTH_STABILITY_BOUNDARY_PRESET,
  UNIT_3_3_ROOT_LOCUS_RULES_PRESET,
  UNIT_3_4_ROOT_LOCUS_READING_VALIDATION_PRESET,
  UNIT_3_5_ZERO_DYNAMIC_IMPROVEMENT_PRESET,
  UNIT_3_6_ZERO_DESIGN_WORKSHOP_PRESET,
  UNIT_3_7_STEADY_ERROR_LOW_FREQUENCY_COMPENSATION_PRESET,
  UNIT_3_8_FREQUENCY_DOMAIN_TRANSLATION_JUDGMENT_PRESET,
  UNIT_3_9_CROSS_DOMAIN_MAPPING_LAB_PRESET,
  UNIT_4_1_DESIGN_TASK_EXPRESSION_PRESET,
  UNIT_4_2_CONTROLLER_SELECTION_FIRST_START_PRESET,
  UNIT_4_3_INITIAL_SCHEME_PRACTICE_FIRST_VALIDATION_PRESET,
  UNIT_4_4_FIXED_STRUCTURE_OPTIMIZATION_MODELING_PRESET,
  UNIT_4_5_CONSTRAINT_AWARE_PARAMETER_OPTIMIZATION_PRESET,
  UNIT_4_6_FIXED_STRUCTURE_BOUNDARY_STRUCTURAL_ENCODING_PRESET,
  UNIT_4_7_DESTROYER_HIFI_DESIGN_CLOSURE_PRESET,
  UNIT_5_1_LINEAR_BACKBONE_BOUNDARIES_PRESET,
];
