/**
 * 预置教案统一出口
 */

import { CRUISE_COMFORT_PRESET } from './cruise-comfort';
import { LESSON_02_MODELING_PRESET } from './lesson-02-modeling';
import { LESSON_06_JUDGE_BENCH_PRESET } from './lesson-06-judge-bench';
import { LESSON_07_UNDERDAMPED_PRESET } from './lesson-07-underdamped';

export {
  CRUISE_COMFORT_PRESET,
  LESSON_02_MODELING_PRESET,
  LESSON_06_JUDGE_BENCH_PRESET,
  LESSON_07_UNDERDAMPED_PRESET,
};

export const ALL_PRESETS = [
  LESSON_02_MODELING_PRESET,
  LESSON_06_JUDGE_BENCH_PRESET,
  LESSON_07_UNDERDAMPED_PRESET,
  CRUISE_COMFORT_PRESET,
];
