import { ResourceType } from '@prisma/client';

import type { PresetLessonConfig } from '../types';

export const L2A_TIME_DOMAIN_FASTTRACK_PRESET: PresetLessonConfig = {
  key: 'l2a-time-domain-fasttrack-v1',
  title: 'L-2a：三张面孔，同一系统 · 时域直觉速通',
  description: '围绕船舶航向阶跃响应，在精品课堂双端同步模式下建立时域直觉。',
  totalDuration: 79,
  thumbnail: '/images/presets/lesson-07-underdamped.svg',
  tags: ['精品课程', '时域分析', '二阶系统', '阻尼比', '自然频率'],
  items: [
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 1,
      title: '知识图谱定位',
      description: '确认 L-2a 在课程链路中的位置。',
      config: {
        mode: 'play',
        config: {
          id: 'l2a-knowledge-map',
          type: 'video',
          title: '知识图谱定位',
          sourceType: 'placeholder',
          primarySource: '/assets/placeholder-underdamped.svg',
          splitMode: 'none',
          narration: '从传递函数与极点，走到时域直觉的第一站。',
          description: 'L-2a 精品课堂入口占位资源。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },
    {
      stage: 'BRIDGE_IN',
      order: 2,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 6,
      title: '导入：情境展示与收拢',
      description: '观察船舶转向曲线，建立家族、指标、参数三条主线。',
      config: {
        mode: 'play',
        config: {
          id: 'l2a-bridge-poll',
          type: 'poll',
          question: '你从这条曲线里最先注意到什么？',
          options: [
            { key: 'A', text: '是否冲过目标值', color: '#38bdf8' },
            { key: 'B', text: '多久才真正稳定', color: '#22c55e' },
            { key: 'C', text: '是否来回振荡', color: '#f59e0b' },
            { key: 'D', text: '我还说不清楚', color: '#ef4444' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 45,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'classroom-objective',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 2,
      title: '今天的目标',
      description: '只建直觉，不做推导。',
      config: {
        mode: 'play',
        config: {
          id: 'l2a-objective-card',
          type: 'objective',
          title: 'L-2a 今日目标',
          objectives: [
            { id: 'obj-1', type: 'knowledge', description: '识别响应家族', badgeName: '家族辨识者', badgeIcon: 'Activity', unlocked: false },
            { id: 'obj-2', type: 'ability', description: '理解 Mₚ、tₛ、tᵣ', badgeName: '指标判读者', badgeIcon: 'Target', unlocked: false },
            { id: 'obj-3', type: 'ability', description: '理解 ζ 与 ωₙ 的方向性影响', badgeName: '参数观察者', badgeIcon: 'Gauge', unlocked: false },
            { id: 'obj-4', type: 'value', description: '知道时域视角的局限', badgeName: '视角切换者', badgeIcon: 'Sparkles', unlocked: false },
          ],
          showUnlockAnimation: true,
        },
      },
    },
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'lesson07-damping-quick-check',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '前测',
      description: '复盘极点稳定性与超调直觉。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 1,
      registryId: 'lesson07-pole-manipulator',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 13,
      title: '四种响应家族',
      description: '从极点位置出发识别过阻尼、欠阻尼、临界阻尼与不稳定。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      registryId: 'lesson07-response-explorer',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 13,
      title: '三个性能指标',
      description: '从同一条曲线中读出 Mₚ、tₛ、tᵣ。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      registryId: 'lesson07-response-explorer',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 17,
      title: '两个关键参数',
      description: '用工作区验证 ζ 控形状、ωₙ 控速度。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      registryId: 'lesson07-summary-card',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 11,
      title: '速记表与局限性',
      description: '完成规律压缩并过渡到 L-2b / L-2c。',
      config: {},
    },
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'classroom-assessment',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '后测',
      description: '检查家族、指标、参数方向与局限性表达。',
      config: {
        mode: 'play',
        config: {
          id: 'l2a-post-assessment',
          type: 'assessment',
          title: 'L-2a 后测',
          description: '用 3 道选择题和 1 道开放反思确认今天的时域直觉。',
          parameters: [
            { id: 'mp', name: 'Mₚ 判断', symbol: 'Mp', min: 0, max: 1, step: 1, defaultValue: 0 },
            { id: 'ts', name: 'tₛ 判断', symbol: 'ts', min: 0, max: 1, step: 1, defaultValue: 0 },
            { id: 'zeta', name: 'ζ 方向性判断', symbol: 'zeta', min: 0, max: 1, step: 1, defaultValue: 0 },
          ],
          scoring: { baseScore: 100, msiWeight: 1, penaltyPerViolation: 0 },
        },
      },
    },
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'classroom-ai-report',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 3,
      title: '总结与预告',
      description: '回收学习记录，预告 L-2b 与 L-2c。',
      config: {
        mode: 'play',
        config: {
          id: 'l2a-summary-report',
          type: 'ai-report',
          title: 'L-2a 课堂报告',
          reportTemplate:
            '本节课围绕四种家族、三个指标、两个参数与时域局限展开。请教师结合学生记录，自主复盘下一步的根轨迹与频域衔接。',
          visualizations: ['bar'],
          enableVoice: false,
        },
      },
    },
  ],
};
