/**
 * 预置教案：Lesson 08 - 稳定性与稳态误差
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟线下课堂流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_08_STABILITY_ACCURACY_PRESET: PresetLessonConfig = {
  key: 'lesson-08-stability-accuracy-v1',
  title: '稳定性与稳态误差：控制系统首要任务与准确性的度量',
  description: '围绕稳定性判据与稳态误差计算，构建 90 分钟线下课堂的完整学习路径。',
  totalDuration: 90,
  thumbnail: '/images/presets/lesson-08-stability-accuracy.svg',
  tags: ['稳定性', '劳斯判据', '稳态误差', '终值定理', '静态误差系数'],
  items: [
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '导入：稳定先于一切',
      description: '用工程事故对比引出“稳定是首要任务”的直觉。',
      config: {
        mode: 'play',
        config: {
          id: 'video-stability-intro',
          type: 'video',
          title: '导入：稳定先于一切',
          sourceType: 'placeholder',
          primarySource: '/assets/placeholder-stability.svg',
          splitMode: 'none',
          narration: '控制系统的第一任务不是“快”，而是“稳”。不稳定的系统没有任何指标值得讨论。',
          description: '对比稳定与不稳定的工程后果，建立稳定意识。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },
    {
      stage: 'BRIDGE_IN',
      order: 2,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '投票：好控制的第一标准',
      description: '收集学生对“稳定、准确、快速”的优先级判断。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-stability-priority',
          type: 'poll',
          question: '如果只能选择一个指标，你认为控制系统最重要的是？',
          options: [
            { key: 'A', text: '稳定性（不发散）', color: '#22c55e' },
            { key: 'B', text: '准确性（稳态误差小）', color: '#3b82f6' },
            { key: 'C', text: '快速性（响应更快）', color: '#f59e0b' },
            { key: 'D', text: '经济性（能耗低）', color: '#ef4444' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 40,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'classroom-objective',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '稳定性与稳态误差 学习目标',
      description: '明确本节课需要掌握的稳定判据与误差计算能力。',
      config: {
        mode: 'play',
        config: {
          id: 'objective-lesson-08',
          type: 'objective',
          title: '稳定性与稳态误差 学习目标',
          objectives: [
            {
              id: 'obj-1',
              type: 'knowledge',
              description: '理解稳定、临界稳定与不稳定的定义与充要条件',
              badgeName: '稳定守门员',
              badgeIcon: 'ShieldCheck',
              unlocked: false,
            },
            {
              id: 'obj-2',
              type: 'ability',
              description: '能够使用劳斯判据判断系统稳定性并处理特殊情况',
              badgeName: '劳斯判据掌舵人',
              badgeIcon: 'Calculator',
              unlocked: false,
            },
            {
              id: 'obj-3',
              type: 'ability',
              description: '掌握终值定理与静态误差系数法计算稳态误差',
              badgeName: '误差测量师',
              badgeIcon: 'Target',
              unlocked: false,
            },
            {
              id: 'obj-4',
              type: 'value',
              description: '形成稳定优先、精度可量化的工程思维方式',
              badgeName: '工程秩序维护者',
              badgeIcon: 'Scale',
              unlocked: false,
            },
          ],
          showUnlockAnimation: true,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 2,
      registryId: 'lesson08-static-roadmap',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 6,
      title: '课程路线图：从稳定到精度',
      description: '展示本节课的两条主线：稳定判据与稳态误差。',
      config: {},
    },
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'lesson08-stability-precheck',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 15,
      title: '前测：稳定与误差基础',
      description: '检测稳定性判据、终值定理与误差概念的先验掌握情况。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 1,
      registryId: 'lesson08-static-stability-concept',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 6,
      title: '稳定性的概念与充要条件',
      description: '用极点位置解释稳定、临界稳定与不稳定。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      registryId: 'lesson08-routh-guide',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 10,
      title: '参与式学习：劳斯判据速览',
      description: '梳理劳斯表构造规则与判别要点。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      registryId: 'lesson08-routh-practice',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 9,
      title: '参与式学习：劳斯判据练习',
      description: '通过典型情形判断稳定性与正实部根数。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      registryId: 'lesson08-static-routh-table',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 5,
      title: '劳斯表构造与符号判别',
      description: '总结劳斯表填写步骤与变号含义。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 5,
      registryId: 'lesson08-static-error-flow',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 6,
      title: '稳态误差计算流程',
      description: '从误差来源到终值定理的三步法。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 6,
      registryId: 'lesson08-steady-error-deck',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 9,
      title: '参与式学习：静态误差系数与系统型别',
      description: '掌握 Kp/Kv/Ka 与输入类型的误差对应关系。',
      config: {},
    },
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'lesson08-post-quiz',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 7,
      title: '后测：稳定与误差综合挑战',
      description: '综合判断稳定性与稳态误差，完成快速测验。',
      config: {},
    },
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'lesson08-summary-card',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '总结与课后思考',
      description: '复盘稳定判据与稳态误差的核心公式与工程启示。',
      config: {},
    },
  ],
};
