/**
 * 预置教案：Lesson 10 - 根轨迹法
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟线下课堂流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_10_ROOT_LOCUS_PRESET: PresetLessonConfig = {
  key: 'lesson-10-root-locus-v1',
  title: '根轨迹法：放眼大局与细节修正',
  description: '以根轨迹法为主线，完成从大局认知、规则速判到细节修正的 90 分钟线下课堂。',
  totalDuration: 90,
  thumbnail: '/images/presets/lesson-10-root-locus.svg',
  tags: ['根轨迹', '模值条件', '相角条件', '分离点', '渐近线', '出射角', '虚轴交点'],
  items: [
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '导入：别只问价格，要看趋势',
      description: '用价格调查的故事引出“放眼大局”的思维方式。',
      config: {
        mode: 'play',
        config: {
          id: 'video-root-locus-intro',
          type: 'video',
          title: '导入：别只问价格，要看趋势',
          sourceType: 'placeholder',
          primarySource: '/assets/lesson-10/root-locus-roadmap.svg',
          splitMode: 'none',
          narration: '求高阶多项式根很难，根轨迹用图形化思考解决“参数变化”的大局问题。',
          description: '从“只问单点”转向“看趋势与范围”。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },
    {
      stage: 'BRIDGE_IN',
      order: 2,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '投票：最难掌握的根轨迹问题',
      description: '快速了解学生对根轨迹难点的认知分布。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-root-locus-pain',
          type: 'poll',
          question: '当系统参数变化时，你最担心哪一件事？',
          options: [
            { key: 'A', text: '稳定性边界在哪里', color: '#22c55e' },
            { key: 'B', text: '画不出根轨迹形状', color: '#38bdf8' },
            { key: 'C', text: '分离点和出射角容易算错', color: '#f97316' },
            { key: 'D', text: '不会从图形反推 K 的范围', color: '#a855f7' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 45,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'classroom-objective',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '根轨迹法 学习目标',
      description: '明确本节课需要掌握的根轨迹规则与修正技巧。',
      config: {
        mode: 'play',
        config: {
          id: 'objective-lesson-10',
          type: 'objective',
          title: '根轨迹法 学习目标',
          objectives: [
            {
              id: 'obj-1',
              type: 'knowledge',
              description: '理解根轨迹的定义及模值/相角条件',
              badgeName: '根轨迹观察者',
              badgeIcon: 'brain',
              unlocked: false,
            },
            {
              id: 'obj-2',
              type: 'ability',
              description: '掌握实轴段、渐近线与分离点等基本绘制法则',
              badgeName: '规则速判员',
              badgeIcon: 'zap',
              unlocked: false,
            },
            {
              id: 'obj-3',
              type: 'ability',
              description: '能够计算出射/入射角并确定虚轴交点',
              badgeName: '细节修正师',
              badgeIcon: 'target',
              unlocked: false,
            },
            {
              id: 'obj-4',
              type: 'value',
              description: '形成“看趋势、找边界、定参数”的图形化思维',
              badgeName: '全局思考者',
              badgeIcon: 'medal',
              unlocked: false,
            },
          ],
          showUnlockAnimation: true,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 2,
      registryId: 'lesson10-static-roadmap',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 4,
      title: '课程路线图：根轨迹法',
      description: '梳理大局与细节修正两条主线。',
      config: {},
    },
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '前测：根轨迹基础认知',
      description: '检测学生对根轨迹定义与规则的先验掌握程度。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-root-locus-precheck',
          type: 'poll',
          question: '哪一句话最准确描述根轨迹法？',
          options: [
            { key: 'A', text: '研究频率响应的幅相变化', color: '#38bdf8' },
            { key: 'B', text: '研究闭环极点随参数变化的轨迹', color: '#22c55e' },
            { key: 'C', text: '只用于求二阶系统的根', color: '#f97316' },
            { key: 'D', text: '只用于稳态误差分析', color: '#a855f7' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 50,
        },
      },
    },
    {
      stage: 'PARTICIPATORY',
      order: 1,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '根轨迹_4_c19f8854',
      duration: 2,
      title: '知识卡片：模值与相角条件',
      description: '判断根轨迹点与对应增益的两条条件。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      registryId: 'lesson10-static-conditions',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 4,
      title: '根轨迹条件：模值与相角',
      description: '用条件判断某点是否属于根轨迹，并求对应增益。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '根轨迹_4_c19f8854',
      duration: 3,
      title: '知识卡片：根轨迹定义与起终点',
      description: '从开环极点出发，指向开环零点与无穷远零点。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      registryId: 'lesson10-root-locus-workshop',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 19,
      title: '参与式学习：根轨迹规则工作坊',
      description: '通过规则速判与细节修正练习建立绘制直觉。',
      config: {
        props: {
          variant: 'overview',
        },
      },
    },
    {
      stage: 'PARTICIPATORY',
      order: 5,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '根轨迹绘制法则_4_f0ea9a49',
      duration: 2,
      title: '知识卡片：根轨迹基本法则',
      description: '分支数、实轴段与渐近线的判别规则。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 6,
      registryId: 'lesson10-static-rules',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 4,
      title: '根轨迹基本法则',
      description: '分支数、实轴段、渐近线与分离点规则汇总。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 7,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '投票：最容易出错的细节',
      description: '定位学生对根轨迹细节的薄弱点。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-root-locus-detail',
          type: 'poll',
          question: '你认为根轨迹哪一项最容易算错？',
          options: [
            { key: 'A', text: '分离点位置', color: '#f97316' },
            { key: 'B', text: '渐近线角度与中心', color: '#38bdf8' },
            { key: 'C', text: '出射/入射角', color: '#22c55e' },
            { key: 'D', text: '虚轴交点', color: '#a855f7' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 40,
        },
      },
    },
    {
      stage: 'PARTICIPATORY',
      order: 8,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '根轨迹分离点_4_0e97795c',
      duration: 2,
      title: '知识卡片：分离点与出射角',
      description: '定位轨迹分离点与复极点出射方向。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 9,
      registryId: 'lesson10-static-detail-corrections',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 6,
      title: '细节修正与关键点',
      description: '用角度与交点修正根轨迹的关键细节。',
      config: {},
    },
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'lesson10-root-locus-workshop',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 12,
      title: '后测：根轨迹挑战站',
      description: '完成模值条件、渐近线中心与分离点的综合挑战。',
      config: {
        props: {
          variant: 'challenge',
        },
      },
    },
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'classroom-ai-report',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '总结：根轨迹法课堂报告',
      description: '复盘根轨迹规则掌握情况并输出课堂要点。',
      config: {
        mode: 'play',
        config: {
          id: 'report-root-locus-summary',
          type: 'ai-report',
          title: '课堂报告：根轨迹法',
          reportTemplate: `本节课共有 {totalStudents} 名同学参与根轨迹训练，{completedStudents} 人完成挑战，完成率 {completionRate}%。\n\n课堂高频易错点集中在“分离点判别”和“出射角计算”。\n\n通过本节课学习，同学们掌握了根轨迹的大局判断、模值/相角条件，以及细节修正方法。`,
          visualizations: ['bar', 'pie'],
          enableVoice: true,
          voiceScript: '',
        },
      },
    },
  ],
};
