/**
 * 预置教案：Lesson 02 - 拉氏变换：工程直觉的数学实现
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟线下课堂流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_02_LAPLACE_PRESET: PresetLessonConfig = {
  key: 'lesson-02-laplace-v1',
  title: '拉氏变换：工程直觉的数学实现',
  description: '从 RLC 微分方程出发，建立 s 域直觉，掌握常用定理与反变换方法。',
  totalDuration: 90,
  thumbnail: '/images/presets/lesson-02-laplace.jpg',
  tags: ['拉普拉斯变换', 's 域', '反变换', '初值终值', '卷积定理'],
  items: [
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'lesson02-laplace-bridge-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '导入：RLC 方程的捷径',
      description: '从微分方程求解的痛点切入拉氏变换。',
      config: {},
    },
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'lesson02-laplace-objective-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '学习目标：工程直觉清单',
      description: '确认拉氏变换学习目标。',
      config: {},
    },
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'lesson02-laplace-precheck-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '前测：直觉自查',
      description: '投票 + 典型问题快速诊断。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 1,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '拉普拉斯变换_2_c635236f',
      duration: 2,
      title: '知识卡片：拉氏变换的工程意义',
      description: '理解从时域到 s 域的投影。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      registryId: 'lesson02-laplace-knowledge-deck-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 16,
      title: '参与式学习：拉氏知识卡片',
      description: '串起物理直觉、定理与反变换路径。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '拉氏变换工程动机_2_11001',
      duration: 2,
      title: '知识卡片：s 平面直觉',
      description: 'σ 与 ω 的物理含义。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      registryId: 'lesson02-laplace-property-match-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 18,
      title: '参与式学习：定理速配',
      description: '建立时域操作与 s 域公式的映射。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 5,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '微分定理_2_11002',
      duration: 2,
      title: '知识卡片：常用定理',
      description: '线性、微分、积分、位移与卷积定理。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 6,
      registryId: 'lesson02-laplace-inverse-lab-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 16,
      title: '参与式学习：反变换路径',
      description: '选择部分分式、待定系数与位移定理。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 7,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '部分分式展开_7_d822352e',
      duration: 2,
      title: '知识卡片：反变换方法',
      description: '归纳常见求解套路。',
    },
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'lesson02-laplace-exit-quiz-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 10,
      title: '后测：关键定理出口检测',
      description: '检验初值/终值与位移定理应用。',
      config: {},
    },
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'lesson02-laplace-summary-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '总结与拓展',
      description: '回顾拉氏变换的工程直觉。',
      config: {},
    },
  ],
};
