/**
 * 预置教案：Lesson 17 - 描述函数分析法与自振判别
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟线下课堂流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_17_DESCRIBING_FUNCTION_PRESET: PresetLessonConfig = {
  key: 'lesson-17-describing-function-v1',
  title: '描述函数分析法与自振判别：交点与稳定性',
  description: '围绕负倒描述函数与交点判别，掌握非线性系统自振分析流程。',
  totalDuration: 90,
  thumbnail: '/images/presets/lesson-17-describing-function.svg',
  tags: ['描述函数', '负倒描述函数', '自振', '极限环', '稳定性', '交点判别'],
  items: [
    // ==================== Stage 1: Bridge-in (导入) - 8分钟 ====================
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '导入：系统为何会自振？',
      description: '用工程自振案例引出描述函数分析。',
      config: {
        mode: 'play',
        config: {
          id: 'video-lesson-17-intro',
          type: 'video',
          title: '导入：系统为何会自振？',
          sourceType: 'placeholder',
          primarySource: '/assets/placeholder-judge-stable.svg',
          splitMode: 'none',
          narration: '自振会带来磨损与失效，需要用描述函数方法快速判别。',
          description: '以工程自振案例引出交点判别。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },
    {
      stage: 'BRIDGE_IN',
      order: 2,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '投票：交点意味着什么？',
      description: '收集学生对交点判别的直觉。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-lesson-17-intersection',
          type: 'poll',
          question: '你认为 G(jω) 与 -1/N(A) 交点代表什么？',
          options: [
            { key: 'A', text: '自振存在的必要条件', color: '#f59e0b' },
            { key: 'B', text: '系统一定稳定', color: '#22c55e' },
            { key: 'C', text: '系统一定不稳定', color: '#ef4444' },
            { key: 'D', text: '无意义', color: '#38bdf8' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 45,
        },
      },
    },

    // ==================== Stage 2: Objective (目标) - 8分钟 ====================
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'classroom-objective',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '本节课学习目标',
      description: '明确描述函数分析与自振判别能力。',
      config: {
        mode: 'play',
        config: {
          id: 'objective-lesson-17',
          type: 'objective',
          title: '描述函数分析法与自振判别 学习目标',
          objectives: [
            {
              id: 'obj-1',
              type: 'knowledge',
              description: '理解描述函数法的适用假设与结构前提',
              badgeName: '判别观察员',
              badgeIcon: 'shield',
              unlocked: false,
            },
            {
              id: 'obj-2',
              type: 'ability',
              description: '掌握负倒描述函数的绘制与交点判别方法',
              badgeName: '交点导航员',
              badgeIcon: 'compass',
              unlocked: false,
            },
            {
              id: 'obj-3',
              type: 'ability',
              description: '能判断自振存在性与稳定性',
              badgeName: '自振判别师',
              badgeIcon: 'activity',
              unlocked: false,
            },
            {
              id: 'obj-4',
              type: 'value',
              description: '形成非线性系统快速评估的工程思维',
              badgeName: '系统守衡者',
              badgeIcon: 'balance-scale',
              unlocked: false,
            },
          ],
          showUnlockAnimation: true,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 2,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '课程路线图：假设 → 负倒 → 自振判别',
      description: '梳理描述函数分析的关键流程。',
      config: {
        mode: 'play',
        config: {
          id: 'video-lesson-17-roadmap',
          type: 'video',
          title: '课程路线图',
          sourceType: 'placeholder',
          primarySource: '/assets/placeholder-judge-stable.svg',
          splitMode: 'none',
          narration: '从适用假设出发，建立负倒描述函数与自振判别流程。',
          description: '明确学习路径与关键判别节点。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },

    // ==================== Stage 3: Pre-assessment (前测) - 10分钟 ====================
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'lesson17-df-precheck',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 10,
      title: '前测：判别要点速查',
      description: '检查描述函数分析的基础概念。',
      config: {},
    },

    // ==================== Stage 4: Participatory (参与式学习) - 50分钟 ====================
    {
      stage: 'PARTICIPATORY',
      order: 1,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '描述函数适用条件_5_52003',
      duration: 1,
      title: '知识卡片：描述函数法的基本假设',
      description: '明确适用前提与结构要求。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      registryId: 'lesson17-df-knowledge-deck',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 16,
      title: '参与式学习：描述函数分析知识卡片',
      description: '贯通负倒描述函数与自振判别。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '负倒描述函数_8_159ff256',
      duration: 1,
      title: '知识卡片：负倒描述函数',
      description: '理解 -1/N(A) 的几何意义。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      registryId: 'lesson17-negative-inverse-workshop',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 12,
      title: '参与式学习：负倒描述函数工作坊',
      description: '掌握典型非线性特性曲线。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 5,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '非线性系统稳定性判据_描述函数法__8_2d9b3f16',
      duration: 1,
      title: '知识卡片：非线性系统稳定性判据',
      description: '理解包围关系与稳定性。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 6,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '自振_8_3ed83301',
      duration: 1,
      title: '知识卡片：自振存在条件',
      description: '交点判别自振存在性。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 7,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '稳定的极限环_8_0a23bf90',
      duration: 1,
      title: '知识卡片：自振稳定性判别',
      description: '微小扰动分析判别稳定性。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 8,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '负倒描述函数_8_159ff256',
      duration: 1,
      title: '知识卡片：负倒描述函数绘制',
      description: '掌握典型轨迹形态。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 9,
      registryId: 'lesson17-limit-cycle-lab',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 15,
      title: '参与式学习：自振判别实验室',
      description: '根据交点与扰动判断自振稳定性。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 10,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '自振_8_3ed83301',
      duration: 1,
      title: '知识卡片：自振参数求解',
      description: '通过幅值与相位方程求解 A 与 ω。',
    },

    // ==================== Stage 5: Post-assessment (后测) - 8分钟 ====================
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'lesson17-df-exit-quiz',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '后测：自振判别速测',
      description: '检验交点判别与参数求解。',
      config: {},
    },

    // ==================== Stage 6: Summary (总结) - 6分钟 ====================
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'lesson17-summary-card',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 6,
      title: '总结与拓展',
      description: '回顾描述函数分析与自振判别主线。',
      config: {},
    },
  ],
};
