/**
 * 预置教案：Lesson 11 - 参数根轨迹与图形化思考
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟线下课堂流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_11_PARAMETER_ROOT_LOCUS_PRESET: PresetLessonConfig = {
  key: 'lesson-11-parameter-root-locus-v1',
  title: '参数根轨迹：广义定义与图形化思考',
  description: '从参数根轨迹的广义定义出发，训练稳定范围判断与图形化思考流程。',
  totalDuration: 90,
  thumbnail: '/images/presets/lesson-11-parameter-root-locus.svg',
  tags: ['参数根轨迹', '等效开环', '稳定范围', '图形化思考', '虚轴交点', '主导极点'],
  items: [
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '导入：当参数不是 K 时怎么办？',
      description: '引出参数变化下的根轨迹分析需求。',
      config: {
        mode: 'play',
        config: {
          id: 'video-lesson-11-intro',
          type: 'video',
          title: '导入：当参数不是 K 时怎么办？',
          sourceType: 'placeholder',
          primarySource: '/assets/lesson-11/parameter-root-locus-roadmap.svg',
          splitMode: 'none',
          narration: '参数根轨迹将“任意参数变化”转换为等效开环问题。',
          description: '从参数变化引出稳定范围与性能落点的图形化思考。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },
    {
      stage: 'BRIDGE_IN',
      order: 2,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '投票：参数根轨迹的难点',
      description: '快速了解学生对参数根轨迹卡点的分布。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-lesson-11-pain',
          type: 'poll',
          question: '你最担心哪一步？',
          options: [
            { key: 'A', text: '等效开环传函怎么构造', color: '#38bdf8' },
            { key: 'B', text: '虚轴交点与稳定范围判断', color: '#f97316' },
            { key: 'C', text: '主导极点如何选', color: '#22c55e' },
            { key: 'D', text: '仿真验证步骤', color: '#a855f7' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 45,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'classroom-objective',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '参数根轨迹 学习目标',
      description: '明确本节课参数根轨迹与图形化思考的关键目标。',
      config: {
        mode: 'play',
        config: {
          id: 'objective-lesson-11',
          type: 'objective',
          title: '参数根轨迹 学习目标',
          objectives: [
            {
              id: 'obj-1',
              type: 'knowledge',
              description: '掌握参数根轨迹的广义定义与等效开环变换',
              badgeName: '参数理解者',
              badgeIcon: 'GitBranch',
              unlocked: false,
            },
            {
              id: 'obj-2',
              type: 'ability',
              description: '能够判定稳定范围与虚轴交点',
              badgeName: '稳定边界侦测员',
              badgeIcon: 'Target',
              unlocked: false,
            },
            {
              id: 'obj-3',
              type: 'ability',
              description: '能够选择主导极点并验证动态性能',
              badgeName: '图形化思考师',
              badgeIcon: 'Eye',
              unlocked: false,
            },
            {
              id: 'obj-4',
              type: 'value',
              description: '形成“参数-轨迹-性能”闭环的工程思维',
              badgeName: '工程决策者',
              badgeIcon: 'Medal',
              unlocked: false,
            },
          ],
          showUnlockAnimation: true,
        },
      },
    },
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '前测：参数根轨迹理解',
      description: '检测对参数根轨迹定义与等效开环概念的掌握。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-lesson-11-precheck',
          type: 'poll',
          question: '参数根轨迹最准确的描述是？',
          options: [
            { key: 'A', text: '闭环极点随 K 变化的轨迹', color: '#38bdf8' },
            { key: 'B', text: '闭环极点随任意参数变化的轨迹', color: '#22c55e' },
            { key: 'C', text: '开环极点随参数变化的轨迹', color: '#f97316' },
            { key: 'D', text: '频率响应随参数变化的曲线', color: '#a855f7' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 50,
        },
      },
    },
    {
      stage: 'PARTICIPATORY',
      order: 1,
      registryId: 'lesson11-parameter-root-locus-deck',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 22,
      title: '知识卡片：参数根轨迹广义定义',
      description: '掌握等效开环、稳定范围与图形化思考主线。',
      config: {
        props: {},
      },
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      registryId: 'lesson11-static-roadmap',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 4,
      title: '课程路线图：参数根轨迹',
      description: '梳理广义定义与图形化思考两条主线。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      registryId: 'lesson11-static-equivalent-open-loop',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 5,
      title: '等效开环转化步骤',
      description: '整理特征方程并构造等效开环传函。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      registryId: 'lesson11-graphical-thinking-workshop',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 18,
      title: '参与式学习：图形化思考工作坊',
      description: '通过案例问题训练参数根轨迹的分析流程。',
      config: {
        props: {},
      },
    },
    {
      stage: 'PARTICIPATORY',
      order: 5,
      registryId: 'lesson11-static-visual-workflow',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 5,
      title: '图形化思考到仿真验证',
      description: '根轨迹到响应验证的流程与代码示意。',
      config: {},
    },
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '后测：参数稳定范围判断',
      description: '检验虚轴交点与稳定范围的判定能力。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-lesson-11-postcheck',
          type: 'poll',
          question: '确定参数稳定范围的关键依据是？',
          options: [
            { key: 'A', text: '虚轴交点对应的参数值', color: '#22c55e' },
            { key: 'B', text: '渐近线角度', color: '#38bdf8' },
            { key: 'C', text: '实轴段长度', color: '#f97316' },
            { key: 'D', text: '出射角大小', color: '#a855f7' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 50,
        },
      },
    },
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'lesson11-summary-card',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '总结与拓展',
      description: '回顾参数根轨迹与图形化思考的关键步骤。',
      config: {
        props: {},
      },
    },
    {
      stage: 'SUMMARY',
      order: 2,
      registryId: 'classroom-ai-report',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 3,
      title: 'AI 课堂报告',
      description: '总结学生在参数根轨迹分析中的共性问题。',
      config: {
        mode: 'play',
        config: {
          id: 'ai-report-lesson-11',
          type: 'ai-report',
          title: '参数根轨迹课堂总结',
          summary: '本节课强调参数根轨迹广义定义与图形化思考流程。',
          metrics: [
            { label: '稳定范围判断', value: '待统计' },
            { label: '主导极点选择', value: '待统计' },
            { label: '仿真验证意识', value: '待统计' },
          ],
          insights: [
            '多数同学能够完成等效开环变换，但在虚轴交点判断上仍需练习。',
            '需要强化“选极点 → 反推参数 → 仿真验证”的闭环流程。',
          ],
          recommendations: [
            '建议课后用 Matlab 验证两组不同参数的阶跃响应差异。',
            '结合频域方法补充稳定裕度分析。',
          ],
        },
      },
    },
  ],
};
