/**
 * 预置教案：Lesson 07 - 衰减振荡·欠阻尼二阶系统
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_07_UNDERDAMPED_PRESET: PresetLessonConfig = {
  key: 'lesson-07-underdamped-v1',
  title: '衰减振荡·欠阻尼二阶系统',
  description: '围绕欠阻尼二阶系统的标准型、响应指标与参数权衡开展 90 分钟线下课堂。',
  totalDuration: 90,
  thumbnail: '/images/presets/lesson-07-underdamped.svg',
  tags: ['时域分析', '二阶系统', '欠阻尼', '衰减振荡', '性能指标'],
  items: [
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '导入：衰减振荡的直觉',
      description: '建立阻尼比与振荡衰减的感性认知。',
      config: {
        mode: 'play',
        config: {
          id: 'video-underdamped-intro',
          type: 'video',
          title: '导入：衰减振荡的直觉',
          sourceType: 'placeholder',
          primarySource: '/assets/placeholder-underdamped.svg',
          splitMode: 'none',
          narration: '当系统受到扰动，响应会像弹簧一样振荡并逐渐衰减。阻尼比决定了它“晃多久、晃多高”。',
          description: '欠阻尼系统的响应既有振荡也有衰减，是控制系统最常见的动态特征。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },
    {
      stage: 'BRIDGE_IN',
      order: 2,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 3,
      title: '投票：阻尼比变大时的响应变化',
      description: '激活学生对阻尼比直觉的讨论。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-underdamped-intuition',
          type: 'poll',
          question: '阻尼比增大时，欠阻尼系统的阶跃响应通常会怎样变化？',
          options: [
            { key: 'A', text: '超调变大、振荡持续更久', color: '#ef4444' },
            { key: 'B', text: '超调减小、衰减更快', color: '#22c55e' },
            { key: 'C', text: '频率变高、峰值更早出现', color: '#38bdf8' },
            { key: 'D', text: '响应变慢但超调不变', color: '#f59e0b' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 45,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'classroom-objective',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '衰减振荡 学习目标',
      description: '明确本节课需要掌握的知识与能力。',
      config: {
        mode: 'play',
        config: {
          id: 'card-lesson-objectives',
          type: 'objective',
          title: '衰减振荡 学习目标',
          objectives: [
            {
              id: 'obj-1',
              type: 'knowledge',
              description: '掌握二阶系统标准型与欠阻尼判据',
              badgeName: '标准型掌舵人',
              badgeIcon: 'DraftingCompass',
              unlocked: false,
            },
            {
              id: 'obj-2',
              type: 'ability',
              description: '能够利用阻尼比与自然频率描述响应形态',
              badgeName: '振荡解读师',
              badgeIcon: 'Activity',
              unlocked: false,
            },
            {
              id: 'obj-3',
              type: 'ability',
              description: '能估算超调量、峰值时间与调节时间',
              badgeName: '指标判读官',
              badgeIcon: 'Target',
              unlocked: false,
            },
            {
              id: 'obj-4',
              type: 'value',
              description: '形成用指标描述响应品质的工程表达习惯',
              badgeName: '工程表达者',
              badgeIcon: 'ShieldCheck',
              unlocked: false,
            },
          ],
          showUnlockAnimation: true,
        },
      },
    },
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'lesson07-damping-quick-check',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '前测：欠阻尼速判',
      description: '检查标准型、欠阻尼判据与性能指标基础认知。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 1,
      registryId: 'lesson07-static-classification',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 5,
      title: '二阶系统传递函数与分类',
      description: '梳理标准型结构与阻尼比分类。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      registryId: 'lesson07-second-order-theory',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 20,
      title: '参与式学习：二阶系统标准型',
      description: '建立标准型、极点位置与性能指标之间的联系。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      registryId: 'lesson07-static-step-response',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 5,
      title: '单位阶跃响应与指标',
      description: '明确超调量、峰值时间、调节时间与上升时间的定义。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      registryId: 'lesson07-response-explorer',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 27,
      title: '参与式学习：衰减振荡实验室',
      description: '通过调参观察响应曲线，完成两轮挑战。',
      config: {},
    },
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'lesson07-parameter-challenge',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '后测：参数匹配挑战',
      description: '根据目标指标提交参数并获取评分。',
      config: {},
    },
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'lesson07-summary-card',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '总结与拓展',
      description: '复盘欠阻尼二阶系统关键概念与课后思考。',
      config: {},
    },
  ],
};
