/**
 * 预置教案：Lesson 09 - 校正与时域综合
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟线下课堂流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_09_CORRECTION_TIME_DOMAIN_PRESET: PresetLessonConfig = {
  key: 'lesson-09-correction-time-domain-v1',
  title: '校正与时域综合：实现控制的手段与验证路径',
  description: '以校正方法为主线，结合航向系统案例，完成时域综合分析与性能验证。',
  totalDuration: 90,
  thumbnail: '/images/presets/lesson-09-correction-time-domain.svg',
  tags: ['系统校正', '比例微分', '输出反馈', '前馈补偿', '扰动补偿', '时域综合'],
  items: [
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '导入：校正让系统更稳更快',
      description: '用“稳、快、准”的目标引出校正的必要性。',
      config: {
        mode: 'play',
        config: {
          id: 'video-correction-intro',
          type: 'video',
          title: '导入：校正让系统更稳更快',
          sourceType: 'placeholder',
          primarySource: '/assets/lesson-09/intro-correction.svg',
          splitMode: 'none',
          narration: '校正就是在系统中加入可调装置，让控制更稳、更快、更准。',
          description: '从性能目标切入，建立“结构改造 → 性能提升”的直觉。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },
    {
      stage: 'BRIDGE_IN',
      order: 2,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 3,
      title: '投票：你最想改善的指标',
      description: '快速识别学生对校正目标的关注点。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-correction-priority',
          type: 'poll',
          question: '如果只能先改善一项，你会优先选择？',
          options: [
            { key: 'A', text: '稳：系统不发散', color: '#22c55e' },
            { key: 'B', text: '快：响应更迅速', color: '#f97316' },
            { key: 'C', text: '准：稳态误差更小', color: '#3b82f6' },
            { key: 'D', text: '抗扰：扰动影响更弱', color: '#a855f7' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 40,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'classroom-objective',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '校正与时域综合 学习目标',
      description: '明确校正方法与时域综合分析的关键能力。',
      config: {
        mode: 'play',
        config: {
          id: 'objective-lesson-09',
          type: 'objective',
          title: '校正与时域综合 学习目标',
          objectives: [
            {
              id: 'obj-1',
              type: 'knowledge',
              description: '理解比例-微分控制与输出微分反馈的机理差异',
              badgeName: '校正理解者',
              badgeIcon: 'Sliders',
              unlocked: false,
            },
            {
              id: 'obj-2',
              type: 'ability',
              description: '能够选择前馈补偿或扰动补偿以改善稳态精度',
              badgeName: '补偿策略师',
              badgeIcon: 'Target',
              unlocked: false,
            },
            {
              id: 'obj-3',
              type: 'ability',
              description: '能用时域指标验证校正效果与性能边界',
              badgeName: '时域验收官',
              badgeIcon: 'LineChart',
              unlocked: false,
            },
            {
              id: 'obj-4',
              type: 'value',
              description: '形成“改结构 + 做验证”的工程化思维',
              badgeName: '工程验证者',
              badgeIcon: 'ShieldCheck',
              unlocked: false,
            },
          ],
          showUnlockAnimation: true,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 2,
      registryId: 'lesson09-static-roadmap',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 4,
      title: '课程路线图：校正与时域综合',
      description: '把校正方法与时域综合分析串联成完整路径。',
      config: {},
    },
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'lesson07-damping-quick-check',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '前测：时域指标与阻尼直觉',
      description: '检验欠阻尼判据与时域性能指标的基础掌握情况。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 1,
      registryId: 'lesson09-static-pd-feedback',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 6,
      title: '比例-微分控制 vs 输出微分反馈',
      description: '对比两种增阻尼方式的零点与响应差异。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      registryId: 'sim-pid-v1',
      resourceType: ResourceType.SIMULATION_APP,
      duration: 20,
      title: '参与式学习：参数整定体验',
      description: '拖动 PID 参数观察航向系统时域响应变化。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      registryId: 'lesson09-static-feedforward-disturbance',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 6,
      title: '前馈补偿与扰动补偿',
      description: '理解输入补偿与扰动补偿的作用路径。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      registryId: 'lesson07-response-explorer',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 14,
      title: '参与式学习：响应曲线与阻尼权衡',
      description: '调参观察超调与调节时间，建立时域权衡。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 5,
      registryId: 'lesson09-static-time-domain-workflow',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 6,
      title: '航向系统时域综合流程',
      description: '从稳定性到场景性能的验证流程。',
      config: {},
    },
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'classroom-assessment',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 10,
      title: '后测：校正参数挑战',
      description: '提交校正参数，获得时域性能反馈。',
      config: {
        mode: 'play',
        config: {
          id: 'assessment-correction-challenge',
          type: 'assessment',
          title: '后测：校正参数挑战',
          description: '在满足超调与调节时间约束的同时提升稳态精度。',
          parameters: [
            { id: 'kp', name: '比例系数', symbol: 'Kp', min: 0, max: 5, step: 0.1, defaultValue: 1.2 },
            { id: 'ki', name: '积分系数', symbol: 'Ki', min: 0, max: 1, step: 0.05, defaultValue: 0 },
            { id: 'kd', name: '微分系数', symbol: 'Kd', min: 0, max: 2, step: 0.1, defaultValue: 0.4 },
          ],
          scoring: { baseScore: 100, msiWeight: 1.1, penaltyPerViolation: 8 },
        },
      },
    },
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'classroom-ai-report',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '总结：校正与时域综合报告',
      description: '汇总课堂数据并回顾校正选择与验证路径。',
      config: {
        mode: 'play',
        config: {
          id: 'report-correction-summary',
          type: 'ai-report',
          title: '课堂报告：校正与时域综合',
          reportTemplate: `本节课共有 {totalStudents} 名同学参与校正训练，{completedStudents} 人完成参数挑战，完成率 {completionRate}%。\n\n班级平均得分 {averageScore} 分。常见问题集中在“超调偏大”和“调节时间偏长”。\n\n通过本节课学习，同学们掌握了 PD/输出反馈的差异、前馈与扰动补偿的应用，以及时域综合验证流程。`,
          visualizations: ['bar', 'pie'],
          enableVoice: true,
          voiceScript: '',
        },
      },
    },
  ],
};
