/**
 * 预置教案：Lesson 01 - 反馈：控制原理的核心思想
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟线下课堂流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_01_FEEDBACK_PRESET: PresetLessonConfig = {
  key: 'lesson-01-feedback-v1',
  title: '反馈：控制原理的核心思想',
  description: '从生活案例切入反馈控制思想，建立闭环系统的核心语言。',
  totalDuration: 90,
  thumbnail: '/images/presets/lesson-01-feedback.jpg',
  tags: ['反馈控制', '闭环系统', '控制结构', '鲁棒性', '误差'],
  items: [
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'lesson01-feedback-bridge-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '导入：烧水的控制语言',
      description: '从生活场景识别反馈动作。',
      config: {},
    },
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'lesson01-feedback-objective-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '学习目标：反馈核心能力',
      description: '明确本节课核心能力。',
      config: {},
    },
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'lesson01-feedback-precheck-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '前测：基础概念速判',
      description: '快速检验反馈与闭环基础。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 1,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: 'node-feedback-core',
      duration: 2,
      title: '知识卡片：反馈的核心思想',
      description: '理解误差驱动的闭环逻辑。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      registryId: 'lesson01-feedback-knowledge-deck-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 16,
      title: '参与式学习：反馈知识卡片',
      description: '建立反馈语言与关键概念。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: 'node-control-system-components',
      duration: 2,
      title: '知识卡片：控制系统四要素',
      description: '对象、控制器、执行器与传感器。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      registryId: 'lesson01-component-role-match-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 18,
      title: '参与式学习：组件职责匹配',
      description: '把控制系统要素与职责对齐。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 5,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: 'node-open-closed-loop',
      duration: 2,
      title: '知识卡片：开环与闭环',
      description: '理解反馈带来的闭环优势。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 6,
      registryId: 'lesson01-loop-scenario-lab-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 18,
      title: '参与式学习：场景分类实验',
      description: '通过案例识别开环与闭环系统。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 7,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: 'node-feedback-benefits',
      duration: 2,
      title: '知识卡片：反馈的价值',
      description: '理解反馈对鲁棒性的贡献。',
    },
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'lesson01-feedback-exit-quiz-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '后测：反馈核心要点',
      description: '检验误差、反馈与闭环特征。',
      config: {},
    },
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'lesson01-feedback-summary-v1',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '总结与拓展',
      description: '回顾反馈控制的核心思想。',
      config: {},
    },
  ],
};
