/**
 * 预置教案：Lesson 12 - 频率特性与伯德图
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟线下课堂流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_12_FREQUENCY_BODE_PRESET: PresetLessonConfig = {
  key: 'lesson-12-frequency-bode-v1',
  title: '频率特性与伯德图：换个角度看控制',
  description: '以频率响应为入口，掌握伯德图的近似叠加绘制与读图反推方法。',
  totalDuration: 90,
  thumbnail: '/images/presets/lesson-12-frequency-bode.svg',
  tags: ['频率响应', '伯德图', '对数频率', '分贝', '转折频率', '斜率叠加', '谐振峰'],
  items: [
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '导入：换个角度看控制',
      description: '从正弦稳态响应切入频率视角。',
      config: {
        mode: 'play',
        config: {
          id: 'video-frequency-intro',
          type: 'video',
          title: '导入：换个角度看控制',
          sourceType: 'placeholder',
          primarySource: '/assets/lesson-12/roadmap-frequency-bode.svg',
          splitMode: 'none',
          narration: '频率响应让我们用正弦稳态看系统，把复杂动态转成可叠加的图形语言。',
          description: '从时域转向频域，建立“稳态-幅值-相位”的新视角。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },
    {
      stage: 'BRIDGE_IN',
      order: 2,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '投票：频域最想解决的问题',
      description: '快速了解学生对频域分析的关注点。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-frequency-focus',
          type: 'poll',
          question: '你最想用频域分析解决哪一类问题？',
          options: [
            { key: 'A', text: '画出系统的频率响应', color: '#38bdf8' },
            { key: 'B', text: '判断典型环节的影响', color: '#22c55e' },
            { key: 'C', text: '快速绘制伯德图', color: '#f97316' },
            { key: 'D', text: '从图反推传递函数', color: '#a855f7' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 45,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'classroom-objective',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '频率特性与伯德图 学习目标',
      description: '明确频率响应与伯德图绘制的关键能力。',
      config: {
        mode: 'play',
        config: {
          id: 'objective-lesson-12',
          type: 'objective',
          title: '频率特性与伯德图 学习目标',
          objectives: [
            {
              id: 'obj-1',
              type: 'knowledge',
              description: '能复述频率响应与正弦稳态响应的含义',
              badgeName: '频域翻译官',
              badgeIcon: 'brain',
              unlocked: false,
            },
            {
              id: 'obj-2',
              type: 'ability',
              description: '掌握典型环节的对数幅频特性与斜率规律',
              badgeName: '斜率判读师',
              badgeIcon: 'zap',
              unlocked: false,
            },
            {
              id: 'obj-3',
              type: 'ability',
              description: '能列举伯德图绘制步骤并确定转折频率',
              badgeName: '绘图指挥官',
              badgeIcon: 'target',
              unlocked: false,
            },
            {
              id: 'obj-4',
              type: 'value',
              description: '形成“拆环节 + 叠斜率”的频域思维方式',
              badgeName: '频域建模者',
              badgeIcon: 'medal',
              unlocked: false,
            },
          ],
          showUnlockAnimation: true,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 2,
      registryId: 'lesson12-static-roadmap',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 4,
      title: '课程路线图：频率响应 → 伯德图',
      description: '梳理频率响应与绘图流程的双主线。',
      config: {},
    },
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'lesson12-frequency-precheck',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 10,
      title: '前测：频率响应速判',
      description: '检验频率响应、dB 与斜率的基础掌握情况。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 1,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: 'node-frequency-response-definition',
      duration: 2,
      title: '知识卡片：频率响应的定义',
      description: '用正弦稳态响应定义幅值比与相位差。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      registryId: 'lesson12-static-frequency-response',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 4,
      title: '频率响应与幅相定义',
      description: '建立 |G(jω)| 与 φ(ω) 的直观理解。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: 'node-bode-log-scale',
      duration: 2,
      title: '知识卡片：Bode 图与对数坐标',
      description: '掌握对数频率与分贝坐标的作用。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: 'node-bode-approx-steps',
      duration: 2,
      title: '知识卡片：伯德图绘制步骤',
      description: '明确尾 1 标准型、转折频率与叠加流程。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 5,
      registryId: 'lesson12-bode-step-sorter',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 9,
      title: '参与式学习：绘制步骤排序',
      description: '按正确流程整理伯德图绘制步骤。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 6,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: 'node-typical-link-slopes',
      duration: 2,
      title: '知识卡片：典型环节斜率规律',
      description: '理解零极点对斜率的叠加贡献。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 7,
      registryId: 'lesson12-bode-slope-puzzle',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 14,
      title: '参与式学习：斜率叠加拼图',
      description: '拖拽斜率卡片完成转折频率分段叠加。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 8,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: 'node-resonance-peak',
      duration: 2,
      title: '知识卡片：振荡环节与谐振峰',
      description: '识别谐振峰并理解修正必要性。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 9,
      registryId: 'lesson12-bode-plot-recognition',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 11,
      title: '参与式学习：伯德图识别',
      description: '根据幅频曲线识别典型环节与共振峰。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 10,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: 'node-bode-from-plot',
      duration: 2,
      title: '知识卡片：读图反推传函',
      description: '通过斜率变化定位零极点结构。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 11,
      registryId: 'lesson12-static-bode-steps',
      resourceType: ResourceType.STATIC_MEDIA,
      duration: 4,
      title: '近似叠加绘图流程',
      description: '用示意图回顾转折频率与斜率变化。',
      config: {},
    },
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'lesson12-bode-post-quiz',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '后测：伯德图关键要点',
      description: '检验绘制流程与斜率叠加的掌握程度。',
      config: {},
    },
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'lesson12-summary-card',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 5,
      title: '总结与拓展',
      description: '复盘频率响应与伯德图的核心结论。',
      config: {},
    },
  ],
};
