/**
 * 预置教案：Lesson 16 - 非线性系统与描述函数基础
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟线下课堂流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_16_NONLINEAR_BASICS_PRESET: PresetLessonConfig = {
  key: 'lesson-16-nonlinear-basics-v1',
  title: '非线性系统与描述函数基础：从现象到模型',
  description: '从工程非线性现象切入，建立描述函数与谐波线性化的核心直觉。',
  totalDuration: 90,
  thumbnail: '/images/presets/lesson-16-nonlinear.svg',
  tags: ['非线性系统', '描述函数', '谐波线性化', '继电器', '饱和', '死区', '间隙'],
  items: [
    // ==================== Stage 1: Bridge-in (导入) - 8分钟 ====================
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '导入：非线性从何而来？',
      description: '从工程限幅与摩擦现象切入非线性系统。',
      config: {
        mode: 'play',
        config: {
          id: 'video-lesson-16-intro',
          type: 'video',
          title: '导入：非线性从何而来？',
          sourceType: 'placeholder',
          primarySource: '/assets/placeholder-judge-stable.svg',
          splitMode: 'none',
          narration: '实际系统普遍存在饱和、死区与间隙，线性只是局部近似。',
          description: '用工程限幅案例引出非线性系统。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },
    {
      stage: 'BRIDGE_IN',
      order: 2,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '投票：最常见的非线性现象？',
      description: '了解学生对非线性特性的直觉认知。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-lesson-16-nonlinear',
          type: 'poll',
          question: '你在工程系统中最常见的非线性是？',
          options: [
            { key: 'A', text: '饱和/限幅', color: '#f59e0b' },
            { key: 'B', text: '死区/不灵敏区', color: '#22c55e' },
            { key: 'C', text: '间隙/回差', color: '#38bdf8' },
            { key: 'D', text: '继电/滞环', color: '#a855f7' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 45,
        },
      },
    },

    // ==================== Stage 2: Objective (目标) - 8分钟 ====================
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'classroom-objective',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '本节课学习目标',
      description: '明确非线性系统与描述函数的核心能力。',
      config: {
        mode: 'play',
        config: {
          id: 'objective-lesson-16',
          type: 'objective',
          title: '非线性系统与描述函数基础 学习目标',
          objectives: [
            {
              id: 'obj-1',
              type: 'knowledge',
              description: '识别非线性系统的特殊性质与典型来源',
              badgeName: '非线性观察员',
              badgeIcon: 'sparkles',
              unlocked: false,
            },
            {
              id: 'obj-2',
              type: 'ability',
              description: '理解谐波线性化与描述函数的定义方法',
              badgeName: '谐波转换师',
              badgeIcon: 'wave-sine',
              unlocked: false,
            },
            {
              id: 'obj-3',
              type: 'ability',
              description: '掌握继电器/饱和/死区/间隙等典型非线性特性',
              badgeName: '特性识别官',
              badgeIcon: 'target',
              unlocked: false,
            },
            {
              id: 'obj-4',
              type: 'value',
              description: '形成非线性近似分析的工程意识',
              badgeName: '近似分析师',
              badgeIcon: 'compass',
              unlocked: false,
            },
          ],
          showUnlockAnimation: true,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 2,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '课程路线图：现象 → 描述函数 → 典型特性',
      description: '梳理非线性基础与描述函数的方法主线。',
      config: {
        mode: 'play',
        config: {
          id: 'video-lesson-16-roadmap',
          type: 'video',
          title: '课程路线图',
          sourceType: 'placeholder',
          primarySource: '/assets/placeholder-judge-stable.svg',
          splitMode: 'none',
          narration: '先识别非线性，再进入描述函数方法与典型特性。',
          description: '明确课堂学习路径。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },

    // ==================== Stage 3: Pre-assessment (前测) - 10分钟 ====================
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'lesson16-nonlinear-precheck',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 10,
      title: '前测：非线性速判',
      description: '快速检查非线性系统与描述函数概念。',
      config: {},
    },

    // ==================== Stage 4: Participatory (参与式学习) - 50分钟 ====================
    {
      stage: 'PARTICIPATORY',
      order: 1,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '非线性系统_8_4ccc0148',
      duration: 1,
      title: '知识卡片：非线性系统的普遍性',
      description: '认识非线性是工程系统的常态。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '非线性系统_8_4ccc0148',
      duration: 1,
      title: '知识卡片：非线性系统的特殊性质',
      description: '理解叠加失效与多平衡点现象。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      registryId: 'lesson16-nonlinear-knowledge-deck',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 16,
      title: '参与式学习：非线性知识卡片',
      description: '用卡片梳理非线性现象与描述函数。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '描述函数法_8_849fa8a1',
      duration: 1,
      title: '知识卡片：谐波线性化',
      description: '理解基波近似思想。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 5,
      registryId: 'lesson16-harmonic-linearization-guide',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 12,
      title: '参与式学习：谐波线性化导航',
      description: '掌握描述函数推导的关键步骤。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 6,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '描述函数法_8_849fa8a1',
      duration: 1,
      title: '知识卡片：描述函数定义',
      description: '明确 N(A) 的物理含义。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 7,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '继电特性_8_0676d186',
      duration: 1,
      title: '知识卡片：理想继电器描述函数',
      description: '掌握继电器特性 N(A) 公式。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 8,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '饱和特性_8_e55b1fb5',
      duration: 1,
      title: '知识卡片：饱和特性描述函数',
      description: '理解限幅对幅值的影响。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 9,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '死区特性_8_9ed850fc',
      duration: 1,
      title: '知识卡片：死区特性描述函数',
      description: '理解不灵敏区的影响。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 10,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '间隙特性_8_51523138',
      duration: 1,
      title: '知识卡片：滞环与间隙特性',
      description: '理解复数描述函数的来源。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 11,
      registryId: 'lesson16-nonlinear-feature-match',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 14,
      title: '参与式学习：非线性特性识别',
      description: '将工程现象映射到典型非线性环节。',
      config: {},
    },

    // ==================== Stage 5: Post-assessment (后测) - 8分钟 ====================
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'lesson16-nonlinear-exit-quiz',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 8,
      title: '后测：描述函数要点',
      description: '检验描述函数与典型非线性特性。',
      config: {},
    },

    // ==================== Stage 6: Summary (总结) - 6分钟 ====================
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'lesson16-summary-card',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 6,
      title: '总结与拓展',
      description: '回顾非线性系统与描述函数基础。',
      config: {},
    },
  ],
};
