/**
 * 预置教案：Lesson 05 - 方框图、信号流图与梅森公式
 *
 * 基于 BOPPPS 教学框架设计的 90 分钟线下课堂流程
 */

import { ResourceType } from '@prisma/client';
import type { PresetLessonConfig } from '../types';

export const LESSON_05_STRUCTURE_TOPOLOGY_PRESET: PresetLessonConfig = {
  key: 'lesson-05-structure-topology-v1',
  title: '方框图、信号流图与梅森公式',
  description: '以结构图、信号流图与梅森公式为主线，完成拓扑建模与公式化求解。',
  totalDuration: 90,
  tags: ['方框图', '信号流图', '梅森公式', '拓扑', '前向通路', '回路'],
  items: [
    // ==================== Stage 1: Bridge-in (导入) - 10分钟 ====================
    {
      stage: 'BRIDGE_IN',
      order: 1,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '导入：为什么要画结构图？',
      description: '从复杂系统“看不清关系”引入拓扑表达。',
      config: {
        mode: 'play',
        config: {
          id: 'video-lesson-05-intro',
          type: 'video',
          title: '结构图与信号流图的价值',
          sourceType: 'placeholder',
          primarySource: '/assets/lesson-05/structure-intro.svg',
          splitMode: 'none',
          narration: '拓扑不变，表达多样。结构图和信号流图是同一件事的不同视角。',
          description: '引出结构图与信号流图的统一性。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },
    {
      stage: 'BRIDGE_IN',
      order: 2,
      registryId: 'classroom-poll',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 6,
      title: '投票：你最容易卡在哪一步？',
      description: '收集结构图与信号流图的学习痛点。',
      config: {
        mode: 'play',
        config: {
          id: 'poll-lesson-05-pain',
          type: 'poll',
          question: '你觉得结构图/信号流图最难的是？',
          options: [
            { key: 'A', text: '移位规则记不住', color: '#38bdf8' },
            { key: 'B', text: '前向通路/回路数不清', color: '#f59e0b' },
            { key: 'C', text: '梅森公式算错', color: '#22c55e' },
            { key: 'D', text: '从方程画图', color: '#a855f7' },
          ],
          multiSelect: false,
          anonymous: false,
          showLiveResults: true,
          timeLimit: 45,
        },
      },
    },

    // ==================== Stage 2: Objective (目标) - 8分钟 ====================
    {
      stage: 'OBJECTIVE',
      order: 1,
      registryId: 'classroom-objective',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '本节课学习目标',
      description: '明确拓扑建模与梅森公式应用能力。',
      config: {
        mode: 'play',
        config: {
          id: 'objective-lesson-05',
          type: 'objective',
          title: '结构图与信号流图 学习目标',
          objectives: [
            {
              id: 'obj-1',
              type: 'knowledge',
              description: '掌握方框图四元素与等效法则',
              badgeName: '结构图观察员',
              badgeIcon: 'book-open',
              unlocked: false,
            },
            {
              id: 'obj-2',
              type: 'ability',
              description: '能将结构图/方程转为信号流图',
              badgeName: '拓扑译员',
              badgeIcon: 'workflow',
              unlocked: false,
            },
            {
              id: 'obj-3',
              type: 'ability',
              description: '正确数出前向通路与回路',
              badgeName: '回路侦探',
              badgeIcon: 'target',
              unlocked: false,
            },
            {
              id: 'obj-4',
              type: 'value',
              description: '熟练应用梅森公式求传函',
              badgeName: '公式掌舵者',
              badgeIcon: 'sparkles',
              unlocked: false,
            },
          ],
          showUnlockAnimation: true,
        },
      },
    },
    {
      stage: 'OBJECTIVE',
      order: 2,
      registryId: 'classroom-video',
      resourceType: ResourceType.INTERACTIVE_COMP,
      duration: 4,
      title: '课程路线图：结构图 -> 信号流图 -> 梅森公式',
      description: '梳理本节课主线。',
      config: {
        mode: 'play',
        config: {
          id: 'video-lesson-05-roadmap',
          type: 'video',
          title: '拓扑主线路线图',
          sourceType: 'placeholder',
          primarySource: '/assets/lesson-05/structure-roadmap.svg',
          splitMode: 'none',
          narration: '从结构图入手，转到信号流图，最后用梅森公式求解。',
          description: '明确各环节学习任务。',
          autoPlay: false,
          autoAdvance: false,
        },
      },
    },

    // ==================== Stage 3: Pre-assessment (前测) - 10分钟 ====================
    {
      stage: 'PRE_ASSESSMENT',
      order: 1,
      registryId: 'lesson05-block-diagram-precheck',
      duration: 10,
      title: '前测：结构图元素速判',
      description: '快速检查结构图元素与等效法则掌握情况。',
      config: {},
    },

    // ==================== Stage 4: Participatory (参与式学习) - 50分钟 ====================
    {
      stage: 'PARTICIPATORY',
      order: 1,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '方块图_1_dbd6301e',
      duration: 1,
      title: '知识卡片：结构图四元素',
      description: '信号线、引出点、综合点、方框。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 2,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '结构图_2_3f312ccc',
      duration: 1,
      title: '知识卡片：由微分方程到结构图',
      description: '按因果顺序连接动态结构。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 3,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '结构图等效变换_2_12001',
      duration: 1,
      title: '知识卡片：串并联与反馈等效',
      description: '三类典型结构快速化简。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 4,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '结构图等效变换_2_12001',
      duration: 1,
      title: '知识卡片：引出点与综合点移位',
      description: '前移/后移规则与信号不变性。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 5,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '结构图简化_2_6d86a775',
      duration: 1,
      title: '知识卡片：结构图化简策略',
      description: '找典型、解交叉、由内向外。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 6,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '信号流图_2_372d4084',
      duration: 1,
      title: '知识卡片：信号流图节点与支路',
      description: '节点是变量，支路是增益。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 7,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '节点_2_1d010af8',
      duration: 1,
      title: '知识卡片：输入/输出/混合节点',
      description: '定位信号源与信号阱。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 8,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '前向通路_2_1f0b4ba2',
      duration: 1,
      title: '知识卡片：前向通路与回路增益',
      description: '梅森公式的基础素材。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 9,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '信号流图_2_372d4084',
      duration: 1,
      title: '知识卡片：结构图转信号流图',
      description: '标变量、定出入、列节点、连支路。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 10,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '信号流图_2_372d4084',
      duration: 1,
      title: '知识卡片：由方程组绘制信号流图',
      description: '初始条件作为输入信号。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 11,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '梅森增益公式_2_419eab0c',
      duration: 1,
      title: '知识卡片：梅森增益公式',
      description: '整体传递函数的核心公式。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 12,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '流图特征式_2_ce0bf70b',
      duration: 1,
      title: '知识卡片：特征式 Delta',
      description: '回路增益与互不接触回路乘积。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 13,
      itemType: 'KNOWLEDGE_NODE',
      knowledgeNodeId: '余因子式_2_1da0d7e8',
      duration: 1,
      title: '知识卡片：余子式 Delta_k',
      description: '剔除相接触回路后的特征式。',
    },
    {
      stage: 'PARTICIPATORY',
      order: 14,
      registryId: 'lesson05-structure-knowledge-deck',
      duration: 9,
      title: '知识卡片：结构图与拓扑主线',
      description: '集中浏览 13 张核心卡片。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 15,
      registryId: 'lesson05-block-diagram-workshop',
      duration: 10,
      title: '互动：结构图化简路线',
      description: '用步骤拼图梳理化简策略。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 16,
      registryId: 'lesson05-signal-flow-lab',
      duration: 9,
      title: '互动：信号流图速练',
      description: '快速确认节点、支路与前向通路。',
      config: {},
    },
    {
      stage: 'PARTICIPATORY',
      order: 17,
      registryId: 'lesson05-mason-loop-challenge',
      duration: 9,
      title: '互动：梅森公式数圈圈',
      description: '数回路、找互不接触回路并计算 Delta。',
      config: {},
    },

    // ==================== Stage 5: Post-assessment (后测) - 8分钟 ====================
    {
      stage: 'POST_ASSESSMENT',
      order: 1,
      registryId: 'lesson05-structure-exit-quiz',
      duration: 8,
      title: '后测：结构图与梅森公式速测',
      description: '检验移位规则与 Delta_k 理解。',
      config: {},
    },

    // ==================== Stage 6: Summary (总结) - 4分钟 ====================
    {
      stage: 'SUMMARY',
      order: 1,
      registryId: 'lesson05-summary-card',
      duration: 4,
      title: '总结：拓扑表达与公式求解',
      description: '回顾主线与课后思考。',
      config: {},
    },
  ],
};

export default LESSON_05_STRUCTURE_TOPOLOGY_PRESET;
