import type { ManifestSubmissionGateInventoryItem } from './shared/manifest-runtime/submission-gate';

const GENERIC_MANIFEST_STEP_HELPER = 'findManifestStepForSubmission';

export const COURSE_RESPONSE_PRODUCING_LESSON_INVENTORY: readonly ManifestSubmissionGateInventoryItem[] = [
  {
    lessonId: '2-1',
    routeSegment: 'unit-2-1-modeling-language',
    manifestPath: 'course-content/runtime/lessons/2-1/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-2-1-modeling-language/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 13,
  },
  {
    lessonId: '3-5',
    routeSegment: 'unit-3-5-zero-dynamic-improvement',
    manifestPath: 'course-content/runtime/lessons/3-5/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-5-zero-dynamic-improvement/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 13,
  },
  {
    lessonId: '3-6',
    routeSegment: 'unit-3-6-zero-design-workshop',
    manifestPath: 'course-content/runtime/lessons/3-6/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-6-zero-design-workshop/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 12,
  },
  {
    lessonId: '3-7',
    routeSegment: 'unit-3-7-steady-error-low-frequency-compensation',
    manifestPath: 'course-content/runtime/lessons/3-7/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-7-steady-error-low-frequency-compensation/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 14,
  },
  {
    lessonId: '3-8',
    routeSegment: 'unit-3-8-frequency-domain-translation-judgment',
    manifestPath: 'course-content/runtime/lessons/3-8/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-8-frequency-domain-translation-judgment/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 13,
  },
  {
    lessonId: '3-9',
    routeSegment: 'unit-3-9-cross-domain-mapping-lab',
    manifestPath: 'course-content/runtime/lessons/3-9/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-9-cross-domain-mapping-lab/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 7,
  },
  {
    lessonId: '4-1',
    routeSegment: 'unit-4-1-design-task-expression',
    manifestPath: 'course-content/runtime/lessons/4-1/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-1-design-task-expression/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 10,
  },
  {
    lessonId: '4-2',
    routeSegment: 'unit-4-2-controller-selection-first-start',
    manifestPath: 'course-content/runtime/lessons/4-2/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-2-controller-selection-first-start/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 14,
  },
  {
    lessonId: '4-3',
    routeSegment: 'unit-4-3-initial-scheme-practice-first-validation',
    manifestPath: 'course-content/runtime/lessons/4-3/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-3-initial-scheme-practice-first-validation/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 15,
  },
  {
    lessonId: '4-4',
    routeSegment: 'unit-4-4-fixed-structure-optimization-modeling',
    manifestPath: 'course-content/runtime/lessons/4-4/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-4-fixed-structure-optimization-modeling/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 9,
  },
  {
    lessonId: '4-5',
    routeSegment: 'unit-4-5-constraint-aware-parameter-optimization',
    manifestPath: 'course-content/runtime/lessons/4-5/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-5-constraint-aware-parameter-optimization/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 3,
  },
  {
    lessonId: '4-6',
    routeSegment: 'unit-4-6-fixed-structure-boundary-structural-encoding',
    manifestPath: 'course-content/runtime/lessons/4-6/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-6-fixed-structure-boundary-structural-encoding/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 3,
  },
  {
    lessonId: '4-7',
    routeSegment: 'unit-4-7-destroyer-hifi-design-closure',
    manifestPath: 'course-content/runtime/lessons/4-7/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-7-destroyer-hifi-design-closure/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 6,
  },
  {
    lessonId: '5-1',
    routeSegment: 'unit-5-1-linear-backbone-boundaries',
    manifestPath: 'course-content/runtime/lessons/5-1/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-1-linear-backbone-boundaries/student-page.tsx',
    manifestGetterName: 'getUNIT_5_1ManifestStepFromManifest',
    minimumResponseSteps: 11,
  },
  {
    lessonId: '5-2',
    routeSegment: 'unit-5-2-nonlinear-analysis-entry',
    manifestPath: 'course-content/runtime/lessons/5-2/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-2-nonlinear-analysis-entry/student-page.tsx',
    manifestGetterName: 'getUNIT_5_2ManifestStepFromManifest',
    minimumResponseSteps: 13,
  },
  {
    lessonId: '5-3',
    routeSegment: 'unit-5-3-mass-coordination-chain',
    manifestPath: 'course-content/runtime/lessons/5-3/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-3-mass-coordination-chain/student-page.tsx',
    manifestGetterName: 'getUNIT_5_3ManifestStepFromManifest',
    minimumResponseSteps: 12,
  },
  {
    lessonId: '5-4',
    routeSegment: 'unit-5-4-data-driven-mpc-transition',
    manifestPath: 'course-content/runtime/lessons/5-4/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-4-data-driven-mpc-transition/student-page.tsx',
    manifestGetterName: 'getUNIT_5_4ManifestStepFromManifest',
    minimumResponseSteps: 14,
  },
  {
    lessonId: '5-5',
    routeSegment: 'unit-5-5-policy-learning-entry-risk',
    manifestPath: 'course-content/runtime/lessons/5-5/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-5-policy-learning-entry-risk/student-page.tsx',
    manifestGetterName: 'getUNIT_5_5ManifestStepFromManifest',
    minimumResponseSteps: 13,
  },
  {
    lessonId: '5-6',
    routeSegment: 'unit-5-6-method-comparison-cold-chain',
    manifestPath: 'course-content/runtime/lessons/5-6/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-6-method-comparison-cold-chain/student-page.tsx',
    manifestGetterName: 'getUNIT_5_6ManifestStepFromManifest',
    minimumResponseSteps: 14,
  },
] as const;

export const REQUIRED_RUNTIME_FIRST_GATE_LESSONS = [
  '2-1',
  '3-5',
  '3-6',
  '3-7',
  '3-8',
  '3-9',
  '4-1',
  '4-2',
  '4-3',
  '4-4',
  '4-5',
  '4-6',
  '4-7',
  '5-1',
  '5-2',
  '5-3',
  '5-4',
  '5-5',
  '5-6',
] as const;
