import type { ManifestSubmissionGateInventoryItem } from './shared/manifest-runtime/submission-gate';
import {
  listInteractiveLessonIdentityRecords,
  resolveInteractiveLessonIdentity,
} from '@/lib/interactive-lesson-identity';

const GENERIC_MANIFEST_STEP_HELPER = 'findManifestStepForSubmission';

export const COURSE_RESPONSE_PRODUCING_LESSON_INVENTORY: readonly ManifestSubmissionGateInventoryItem[] = [
  {
    lessonId: 'cruise-comfort-boppps',
    routeSegment: 'cruise-comfort-boppps',
    manifestPath: 'course-content/runtime/lessons/cruise-comfort-boppps/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/cruise-comfort-standard-course/student-page.tsx',
    courseSourcePath: 'src/lib/cruise-course.ts',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 6,
  },
  {
    lessonId: '1-1',
    routeSegment: 'unit-1-1-see-the-full-picture',
    manifestPath: 'course-content/runtime/lessons/1-1/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-1-1-see-the-full-picture/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 3,
  },
  {
    lessonId: '1-2',
    routeSegment: 'unit-1-2-modeling-from-object-to-system',
    manifestPath: 'course-content/runtime/lessons/1-2/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-1-2-modeling-from-object-to-system/student-page.tsx',
    manifestGetterName: 'getUNIT_1_2ManifestStepFromManifest',
    minimumResponseSteps: 8,
  },
  {
    lessonId: '1-3',
    routeSegment: 'unit-1-3-parameter-pole-migration',
    manifestPath: 'course-content/runtime/lessons/1-3/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-1-3-parameter-pole-migration/student-page.tsx',
    manifestGetterName: 'getUNIT_1_3ManifestStepFromManifest',
    minimumResponseSteps: 7,
  },
  {
    lessonId: '1-4',
    routeSegment: 'unit-1-4-time-frequency-views',
    manifestPath: 'course-content/runtime/lessons/1-4/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-1-4-time-frequency-views/student-page.tsx',
    manifestGetterName: 'getUNIT_1_4ManifestStepFromManifest',
    minimumResponseSteps: 9,
  },
  {
    lessonId: '1-5',
    routeSegment: 'unit-1-5-three-domain-gain-sweep',
    manifestPath: 'course-content/runtime/lessons/1-5/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-1-5-three-domain-gain-sweep/student-page.tsx',
    manifestGetterName: 'getUNIT_1_5ManifestStepFromManifest',
    minimumResponseSteps: 10,
  },
  {
    lessonId: '2-1',
    routeSegment: 'unit-2-1-modeling-language',
    manifestPath: 'course-content/runtime/lessons/2-1/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-2-1-modeling-language/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 13,
  },
  {
    lessonId: '2-2',
    routeSegment: 'unit-2-2-time-domain-response',
    manifestPath: 'course-content/runtime/lessons/2-2/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-2-2-time-response/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 14,
  },
  {
    lessonId: '2-3',
    routeSegment: 'unit-2-3-frequency-response-bode-intro',
    manifestPath: 'course-content/runtime/lessons/2-3/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-2-3-frequency-response/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 14,
  },
  {
    lessonId: '2-4',
    routeSegment: 'unit-2-4-nyquist-margin-entry',
    manifestPath: 'course-content/runtime/lessons/2-4/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-2-4-nyquist-margin-entry/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 14,
  },
  {
    lessonId: '3-1',
    routeSegment: 'unit-3-1-pure-pole-stability-and-dynamics',
    manifestPath: 'course-content/runtime/lessons/3-1/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-1-pure-pole-stability-and-dynamics/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 12,
  },
  {
    lessonId: '3-2',
    routeSegment: 'unit-3-2-routh-stability-boundary',
    manifestPath: 'course-content/runtime/lessons/3-2/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-2-routh-stability-boundary/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 11,
  },
  {
    lessonId: '3-3',
    routeSegment: 'unit-3-3-root-locus-rules',
    manifestPath: 'course-content/runtime/lessons/3-3/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-3-root-locus-rules/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 9,
  },
  {
    lessonId: '3-4',
    routeSegment: 'unit-3-4-root-locus-reading-validation',
    manifestPath: 'course-content/runtime/lessons/3-4/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-4-root-locus-reading-validation/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 13,
  },
  {
    lessonId: '3-5',
    routeSegment: 'unit-3-5-zero-dynamic-improvement',
    manifestPath: 'course-content/runtime/lessons/3-5/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-5-zero-dynamic-improvement/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 13,
  },
  {
    lessonId: '3-6',
    routeSegment: 'unit-3-6-zero-design-workshop',
    manifestPath: 'course-content/runtime/lessons/3-6/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-6-zero-design-workshop/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 12,
  },
  {
    lessonId: '3-7',
    routeSegment: 'unit-3-7-steady-error-low-frequency-compensation',
    manifestPath: 'course-content/runtime/lessons/3-7/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-7-steady-error-low-frequency-compensation/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 14,
  },
  {
    lessonId: '3-8',
    routeSegment: 'unit-3-8-frequency-domain-translation-judgment',
    manifestPath: 'course-content/runtime/lessons/3-8/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-8-frequency-domain-translation-judgment/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 13,
  },
  {
    lessonId: '3-9',
    routeSegment: 'unit-3-9-cross-domain-mapping-lab',
    manifestPath: 'course-content/runtime/lessons/3-9/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-3-9-cross-domain-mapping-lab/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 7,
  },
  {
    lessonId: '4-1',
    routeSegment: 'unit-4-1-design-task-expression',
    manifestPath: 'course-content/runtime/lessons/4-1/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-1-design-task-expression/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 10,
  },
  {
    lessonId: '4-2',
    routeSegment: 'unit-4-2-controller-selection-first-start',
    manifestPath: 'course-content/runtime/lessons/4-2/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-2-controller-selection-first-start/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 14,
  },
  {
    lessonId: '4-3',
    routeSegment: 'unit-4-3-initial-scheme-practice-first-validation',
    manifestPath: 'course-content/runtime/lessons/4-3/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-3-initial-scheme-practice-first-validation/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 15,
  },
  {
    lessonId: '4-4',
    routeSegment: 'unit-4-4-fixed-structure-optimization-modeling',
    manifestPath: 'course-content/runtime/lessons/4-4/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-4-fixed-structure-optimization-modeling/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 9,
  },
  {
    lessonId: '4-5',
    routeSegment: 'unit-4-5-constraint-aware-parameter-optimization',
    manifestPath: 'course-content/runtime/lessons/4-5/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-5-constraint-aware-parameter-optimization/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 3,
  },
  {
    lessonId: '4-6',
    routeSegment: 'unit-4-6-fixed-structure-boundary-structural-encoding',
    manifestPath: 'course-content/runtime/lessons/4-6/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-6-fixed-structure-boundary-structural-encoding/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 3,
  },
  {
    lessonId: '4-7',
    routeSegment: 'unit-4-7-destroyer-hifi-design-closure',
    manifestPath: 'course-content/runtime/lessons/4-7/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-4-7-destroyer-hifi-design-closure/student-page.tsx',
    manifestGetterName: GENERIC_MANIFEST_STEP_HELPER,
    minimumResponseSteps: 6,
  },
  {
    lessonId: '5-1',
    routeSegment: 'unit-5-1-linear-backbone-boundaries',
    manifestPath: 'course-content/runtime/lessons/5-1/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-1-linear-backbone-boundaries/student-page.tsx',
    manifestGetterName: 'getUNIT_5_1ManifestStepFromManifest',
    minimumResponseSteps: 11,
  },
  {
    lessonId: '5-2',
    routeSegment: 'unit-5-2-nonlinear-analysis-entry',
    manifestPath: 'course-content/runtime/lessons/5-2/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-2-nonlinear-analysis-entry/student-page.tsx',
    manifestGetterName: 'getUNIT_5_2ManifestStepFromManifest',
    minimumResponseSteps: 13,
  },
  {
    lessonId: '5-3',
    routeSegment: 'unit-5-3-mass-coordination-chain',
    manifestPath: 'course-content/runtime/lessons/5-3/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-3-mass-coordination-chain/student-page.tsx',
    manifestGetterName: 'getUNIT_5_3ManifestStepFromManifest',
    minimumResponseSteps: 12,
  },
  {
    lessonId: '5-4',
    routeSegment: 'unit-5-4-data-driven-mpc-transition',
    manifestPath: 'course-content/runtime/lessons/5-4/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-4-data-driven-mpc-transition/student-page.tsx',
    manifestGetterName: 'getUNIT_5_4ManifestStepFromManifest',
    minimumResponseSteps: 14,
  },
  {
    lessonId: '5-5',
    routeSegment: 'unit-5-5-policy-learning-entry-risk',
    manifestPath: 'course-content/runtime/lessons/5-5/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-5-policy-learning-entry-risk/student-page.tsx',
    manifestGetterName: 'getUNIT_5_5ManifestStepFromManifest',
    minimumResponseSteps: 13,
  },
  {
    lessonId: '5-6',
    routeSegment: 'unit-5-6-method-comparison-cold-chain',
    manifestPath: 'course-content/runtime/lessons/5-6/interactive-manifest.json',
    studentPagePath: 'src/features/interactive/unit-5-6-method-comparison-cold-chain/student-page.tsx',
    manifestGetterName: 'getUNIT_5_6ManifestStepFromManifest',
    minimumResponseSteps: 14,
  },
] as const;

export const REQUIRED_RUNTIME_FIRST_GATE_LESSONS =
  listInteractiveLessonIdentityRecords().map((record) => record.canonicalId);

export function resolveCourseResponseProducingLessonInventoryItem(
  lessonIdentity: string | null | undefined,
): ManifestSubmissionGateInventoryItem | null {
  const resolved = resolveInteractiveLessonIdentity(lessonIdentity ?? '');
  if (resolved.status !== 'resolved') return null;
  return COURSE_RESPONSE_PRODUCING_LESSON_INVENTORY.find(
    (item) => item.lessonId === resolved.record.canonicalId,
  ) ?? null;
}
