/**
 * Frozen caller denominator captured with the expanded retirement scan roots.
 * Recaptured at c253a4bdee893ae877dca8ab8f1d2468548e6615 (integration merge of PR #2065): caller paths follow the
 * files moved by #2019 and the graph/path redesign, and the census documents
 * that now reference retired symbols are part of the declared denominator.
 */
import type { GraphCaller } from './contracts';

/**
 * Generated artifacts removed from the worktree (the ledger is rebuilt on
 * demand from retained inputs). Their frozen rows stay as historical
 * denominator evidence and are no longer expected in live caller scans.
 */
export const RETIRED_GENERATED_CALLER_PATHS: readonly string[] = [
  'docs/architecture/fitness-budget-ledger.json',
];

export const FROZEN_CALLERS: Readonly<Record<string, readonly GraphCaller[]>> = {
  'registry-read:student-resources-id-metadata-fallback': [
    { path: 'docs/architecture/modular-monolith-charter.json', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith/baseline/census-core.json', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/security/next-major-readiness-2026-06-01.md', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-define-resource-identity-and-generated-registry-index/evidence/caller-denominator.md', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-define-resource-identity-and-generated-registry-index/evidence/characterization.md', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-define-resource-identity-and-generated-registry-index/evidence/foreign-identity-matrix.md', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-define-resource-identity-and-generated-registry-index/evidence/HANDOFF.md', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-define-resource-identity-and-generated-registry-index/evidence/migration-ledger.md', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-separate-resource-eligibility-from-release-activation/evidence/denominator.md', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/caller-denominator.md', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/characterization.md', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/deprecation-ledger.md', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'src/lib/__tests__/resources-api-route.test.ts', symbol: 'src/app/api/resources/[id]/route.ts', callerClass: 'test', kind: 'test' },
  ],
  'eligibility:full-resource-path-readiness-gate': [
    { path: 'docs/architecture/dependency-allowlist.json', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/fitness-budget-allowlist.json', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith-charter.json', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith/baseline/census-core.json', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith/baseline/gates.md', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith/current-head/delta.json', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/trust-boundary-matrix.md', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-cutover-personalization-path-planner/evidence/import-call-graph.md', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-define-resource-identity-and-generated-registry-index/evidence/characterization.md', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-separate-resource-eligibility-from-release-activation/proposal.md', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/characterization.md', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/deprecation-ledger.md', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'historical', kind: 'import' },
    { path: 'scripts/db/generate-resource-field-completion-audit.ts', symbol: 'buildFullResourcePathReadinessGate', callerClass: 'script', kind: 'import' },
    { path: 'src/features/personalization/path-planning/__tests__/plan-learning-path.test.ts', symbol: 'src/lib/full-resource-path-readiness-gate.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/resource-field-completion-audit.test.ts', symbol: 'buildFullResourcePathReadinessGate', callerClass: 'test', kind: 'test' },
  ],
  'eligibility:resource-node-aggregate-ready': [
    { path: 'artifacts/commercial-ui/issue-1437-resource-node-destination/evidence-manifest.json', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'browser', kind: 'import' },
    { path: 'docs/architecture/dependency-allowlist.json', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/fitness-budget-allowlist.json', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith-charter.json', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith/baseline/census-core.json', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith/baseline/cycles.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith/baseline/metrics.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith/post-convergence/hotspots.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/proposals/2026-06-20-map-center.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/proposals/2026-06-21-graph-path.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-06-21-extend-resource-segments-for-kaq-scene-binding/proposal.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-06-22-ingest-media-source-manifests-for-graph-resources/proposal.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-07-07-fix-konling-context-typecheck-debt/tasks.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-07-07-fix-resource-media-rag-typecheck-debt/.buddy/issue.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-07-07-fix-resource-media-rag-typecheck-debt/specs/release-signal-noise-governance/spec.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-define-resource-identity-and-generated-registry-index/evidence/caller-denominator.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-define-resource-identity-and-generated-registry-index/evidence/characterization.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/characterization.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/protected-surfaces.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-09-06-issue-2033-oss/proposal.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-09-07-bind-path-candidates-runtime-assets/proposal.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-09-08-path-planning-consumes-teaching-projection/design.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-09-08-path-planning-consumes-teaching-projection/proposal.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-09-08-redesign-graph-path-experience/design.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/specs/release-signal-noise-governance/spec.md', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'historical', kind: 'import' },
    { path: 'scripts/db/generate-resource-field-completion-audit.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'script', kind: 'import' },
    { path: 'scripts/tests/test-new-resource-semantic-completeness-command.mjs', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'script', kind: 'import' },
    { path: 'src/app/api/teacher/resource-nodes/[nodeId]/route.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'route-api', kind: 'import' },
    { path: 'src/app/api/teacher/resource-nodes/route.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'route-api', kind: 'import' },
    { path: 'src/app/api/teacher/sar-suggested-bindings/review/route.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'route-api', kind: 'import' },
    { path: 'src/app/teacher/resources/resource-nodes/page.tsx', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'browser', kind: 'import' },
    { path: 'src/features/assessment/micro-intervention-outcomes.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/features/assessment/remediation-orchestration.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/features/knowledge/resource-node-workspace-contracts.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/features/personalization/path-planning/__tests__/adaptive-path-strategy-contrast.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/features/personalization/path-planning/__tests__/assemble-plan.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/features/personalization/path-planning/__tests__/control-correction-path-rounds.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/features/personalization/path-planning/__tests__/engineering-resource-order.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/features/personalization/path-planning/__tests__/fixtures/alternative-core-fixture.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/features/personalization/path-planning/__tests__/plan-learning-path.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/features/personalization/path-planning/application/plan-learning-path.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/features/personalization/path-planning/control-correction-path-rounds.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'dynamic' },
    { path: 'src/features/personalization/path-planning/engineering-resource-order.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/features/personalization/path-planning/internal/assemble-plan.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'dynamic' },
    { path: 'src/features/personalization/path-planning/ports.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/features/personalization/path-planning/resource-ranker.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/features/teacher/resources/teacher-resource-node-management.tsx', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'browser', kind: 'import' },
    { path: 'src/lib/__tests__/adaptive-learning-center-ui.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/adaptive-learning-optimization-experiments.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/adaptive-path-journey-control.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/adaptive-path-timeline.client.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/canonical-learning-path-transition.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/konling-agent-runtime.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/resource-feature-history.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/resource-field-completion-audit.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/resource-node-knowledge-workspace-ui.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/resource-node-registry.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/runtime-resource-projections.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/teacher-resource-node-management.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/teaching-projection-path-binding-adapter.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/canonical-resource-binding/runtime-projection.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/control-correction-resource-seed.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/data-governance/__tests__/data-completeness-audit.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/data-governance/__tests__/graph-center.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/data-governance/__tests__/new-resource-semantic-completeness-gate.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/data-governance/__tests__/sar-projection.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/data-governance/__tests__/teacher-kaq-evidence-trace.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/data-governance/__tests__/teacher-prep-pack-generation.test.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/data-governance/control-correction-demo-package.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/data-governance/data-completeness-audit.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/data-governance/graph-center-sources.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/data-governance/graph-center.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/data-governance/new-resource-semantic-completeness-gate.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/data-governance/resource-coverage-matching.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/data-governance/sar-projection.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/data-governance/teacher-prep-pack-generation.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/frequency-response-resource-seed.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/full-resource-path-readiness-gate.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/konling-agent-runtime.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'dynamic' },
    { path: 'src/lib/published-resource-planning.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/resource-feature-history.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/resource-field-completion-audit.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/resource-node-path-readiness-review-batch.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/resource-registry-metadata.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/runtime-resource-projections.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/structured-textbook-runtime.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/teacher-resource-node-data.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/teacher-resource-node-management.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/teaching-projection-path-binding-adapter.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'src/lib/textbook-media-grounding.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'production', kind: 'import' },
    { path: 'tests/issue-1437-resource-node-destination.spec.ts', symbol: 'src/lib/resource-node-registry.ts', callerClass: 'test', kind: 'test' },
  ],
  'knowledge-projection:nodes-list-array-dto': [
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/chapters/46-function-state-flows-batch38.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/chapters/60-function-state-flows-batch52.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/chapters/61-function-state-flows-batch53.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/remediation/audit-remediation-authoring-api-task-consumption-closure/evidence.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/report.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/screenshots/function-state-flows-batch38-manifest.json', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/screenshots/function-state-flows-batch52-manifest.json', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/screenshots/function-state-flows-batch53-manifest.json', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/scripts/capture-batch38.mjs', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/scripts/capture-batch52.mjs', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'artifacts/product-design-audits/full-system-page-function-audit-2026-06-20/scripts/capture-batch53.mjs', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'docs/architecture/modular-monolith-charter.json', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/architecture/modular-monolith/baseline/census-core.json', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/archive/legacy-docs/KNOWLEDGE_REFACTOR_PLAN.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'docs/proposals/course-knowledge-base-governance-source-registry.yaml', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-07-01-audit-remediation-authoring-api-task-consumption-closure/proposal.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-consolidate-versioned-knowledge-surface-read-contracts/evidence/caller-denominator.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-consolidate-versioned-knowledge-surface-read-contracts/evidence/characterization.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-consolidate-versioned-knowledge-surface-read-contracts/evidence/HANDOFF.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-28-consolidate-versioned-knowledge-surface-read-contracts/evidence/migration-ledger.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/caller-denominator.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/characterization.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/deprecation-ledger.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'openspec/changes/archive/2026-08-29-retire-superseded-resource-governance-entrypoints/evidence/HANDOFF.md', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'historical', kind: 'import' },
    { path: 'scripts/tests/test-runtime-knowledge-governance.ts', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'script', kind: 'import' },
    { path: 'src/app/__tests__/authoring-resource-flow-source.test.ts', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/features/knowledge/__tests__/knowledge-nodes-route.test.ts', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/features/knowledge/playlist-builder.tsx', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'src/features/lesson-engine/orchestrator-builder.tsx', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'browser', kind: 'import' },
    { path: 'src/lib/__tests__/authoritative-knowledge-repository.test.ts', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/knowledge-db-fallback-production.real-smoke.test.ts', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/lib/__tests__/shared-react-state-effect-safety.test.ts', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'test', kind: 'test' },
    { path: 'src/resources/interactive-learning/shared/knowledge-cards-data.ts', symbol: 'src/app/api/knowledge/nodes/route.ts', callerClass: 'production', kind: 'import' },
  ],
  'knowledge-projection:client-url-identity-reconstruction': [
  ],
};
