/**
 * 预置教案模块导出
 */

export { PresetLessonList } from './preset-lesson-list';
export { PresetLessonPreview } from './preset-lesson-preview';
export {
  ALL_PRESETS,
  LESSON_01_FEEDBACK_PRESET,
  LESSON_02_LEGACY_MODELING_PRESET,
  LESSON_02_LAPLACE_PRESET,
  LESSON_03_DIFFERENTIAL_MODELING_PRESET,
  LESSON_04_TRANSFER_FUNCTION_PRESET,
  LESSON_05_STRUCTURE_TOPOLOGY_PRESET,
  LESSON_06_JUDGE_BENCH_PRESET,
  LESSON_07_UNDERDAMPED_PRESET,
  LESSON_08_STABILITY_ACCURACY_PRESET,
  LESSON_12_FREQUENCY_BODE_PRESET,
  LESSON_13_PHASE_STABILITY_PRESET,
  LESSON_14_STABILITY_MARGIN_PRESET,
  LESSON_15_SERIES_COMPENSATION_PRESET,
  UNIT_1_2_MODELING_FROM_OBJECT_TO_SYSTEM_PRESET,
  UNIT_1_3_PARAMETER_POLE_MIGRATION_PRESET,
  UNIT_2_1_MODELING_LANGUAGE_PRESET,
  UNIT_2_2_TIME_DOMAIN_RESPONSE_PRESET,
  UNIT_4_5_CONSTRAINT_AWARE_PARAMETER_OPTIMIZATION_PRESET,
} from './presets';
export { BOPPPS_STAGES } from './types';
export type {
  PresetLessonConfig,
  PresetLessonItem,
  PresetLessonSummary,
} from './types';
