pkg load control;

args = argv();
if numel(args) < 4
  error("usage: octave -qf generate_traditional_design_four_panel_data.m output_json Tr Th Kh");
endif

output_path = args{1};
Tr = str2double(args{2});
Th = str2double(args{3});
Kh = str2double(args{4});

K = Kh / (Tr * Th);
wc = 0.040;
phase_boost_deg = 35.0;
phase_boost = phase_boost_deg * pi / 180;
alpha = (1 - sin(phase_boost)) / (1 + sin(phase_boost));
Ti = Th;
Tz = 1 / (wc * sqrt(alpha));
Tp = alpha * Tz;

s = tf("s");
P = K / (s * (Tr * s + 1) * (Th * s + 1));
C_shape = ((Ti * s + 1) / (Ti * s)) * ((Tz * s + 1) / (Tp * s + 1));
Kc = 1 / abs(freqresp(P * C_shape, wc));
C = Kc * C_shape;
L = P * C;

t = linspace(0, 900, 1200);
[diagnosis_step_y, diagnosis_step_t] = step(feedback(P, 1), t);
t_design = linspace(0, 700, 1200);
[step_uncorrected_y, step_uncorrected_t] = step(feedback(P, 1), t_design);
[step_corrected_y, step_corrected_t] = step(feedback(L, 1), t_design);

w = logspace(-4, 0.6, 700);
plant_response = squeeze(freqresp(P, w));
controller_response = squeeze(freqresp(C, w));
corrected_response = squeeze(freqresp(L, w));

gains = logspace(-3, 5, 320);
[plant_num, plant_den] = tfdata(P, "vector");
[controller_num, controller_den] = tfdata(C, "vector");
[corrected_num, corrected_den] = tfdata(L, "vector");

function roots_payload = locus_roots(num, den, gains)
  padded_num = [zeros(1, length(den) - length(num)), num];
  real_parts = zeros(length(gains), length(den) - 1);
  imag_parts = zeros(length(gains), length(den) - 1);
  for i = 1:length(gains)
    r = roots(den + gains(i) * padded_num);
    real_parts(i, :) = real(r).';
    imag_parts(i, :) = imag(r).';
  endfor
  roots_payload = struct("real", real_parts, "imag", imag_parts);
endfunction

function points_payload = complex_points(values)
  points_payload = struct("real", real(values), "imag", imag(values));
endfunction

[gm, pm, wg, wp] = margin(L);
if isnan(pm)
  pm = 0;
endif
if isnan(wp)
  wp = wc;
endif

payload = struct();
payload.design = struct( ...
  "Tr", Tr, ...
  "Th", Th, ...
  "Kh", Kh, ...
  "K", K, ...
  "wc", wc, ...
  "phaseBoostDeg", phase_boost_deg, ...
  "alpha", alpha, ...
  "Ti", Ti, ...
  "Tz", Tz, ...
  "Tp", Tp, ...
  "Kc", Kc, ...
  "phaseMarginDeg", pm, ...
  "phaseMarginFrequency", wp ...
);
payload.diagnosis = struct( ...
  "timeS", diagnosis_step_t(:).', ...
  "stepResponse", diagnosis_step_y(:).', ...
  "bode", struct( ...
    "w", w, ...
    "plantMagDb", 20 * log10(abs(plant_response)), ...
    "plantPhaseDeg", unwrap(angle(plant_response)) * 180 / pi ...
  ), ...
  "nyquist", complex_points(plant_response), ...
  "rootLocus", locus_roots(plant_num, plant_den, gains), ...
  "rootGains", gains, ...
  "plantPoles", complex_points(roots(plant_den)), ...
  "plantZeros", complex_points(roots(plant_num)) ...
);
payload.designCheck = struct( ...
  "timeS", step_uncorrected_t(:).', ...
  "stepUncorrected", step_uncorrected_y(:).', ...
  "stepCorrected", step_corrected_y(:).', ...
  "bode", struct( ...
    "w", w, ...
    "plantMagDb", 20 * log10(abs(plant_response)), ...
    "controllerMagDb", 20 * log10(abs(controller_response)), ...
    "correctedMagDb", 20 * log10(abs(corrected_response)), ...
    "plantPhaseDeg", unwrap(angle(plant_response)) * 180 / pi, ...
    "controllerPhaseDeg", unwrap(angle(controller_response)) * 180 / pi, ...
    "correctedPhaseDeg", unwrap(angle(corrected_response)) * 180 / pi ...
  ), ...
  "uncorrectedRootLocus", locus_roots(plant_num, plant_den, gains), ...
  "correctedRootLocus", locus_roots(corrected_num, corrected_den, gains), ...
  "rootGains", gains, ...
  "uncorrectedPoles", complex_points(roots(plant_den)), ...
  "uncorrectedZeros", complex_points(roots(plant_num)), ...
  "correctedPoles", complex_points(roots(corrected_den)), ...
  "correctedZeros", complex_points(roots(corrected_num)) ...
);

fid = fopen(output_path, "w");
if fid < 0
  error("cannot open output path: %s", output_path);
endif
fprintf(fid, "%s", jsonencode(payload));
fclose(fid);
